/**
 * KrishiSathi - Crop Advisory Rules Seed Data
 * 60+ rules for 10 crops with region-specific soil+season combos + fallbacks
 */

const cropRules = [
  // ============================================================
  // COTTON (Kharif crop, MSP 7121)
  // ============================================================
  {
    crop: 'cotton', soilType: 'black', season: 'kharif', region: 'telangana',
    fertilizer: { type: 'NPK 20:20:20', quantity: '50 kg/acre', schedule: 'Basal dose at sowing, top dressing at 30 and 60 DAS', notes: 'Apply FYM 5 tonnes/acre before sowing' },
    irrigation: { method: 'Drip irrigation', frequency: 'Every 5-7 days', waterPerAcre: '500 litres/day', notes: 'Critical stages: flowering and boll development' },
    pest: { commonPests: ['American Bollworm', 'Pink Bollworm', 'Whitefly'], prevention: 'Install pheromone traps at 5/acre, grow trap crops like marigold', treatment: 'Spray Profenofos 50% EC @2ml/L', spraySchedule: 'At 30, 50, 70, 90 DAS' },
    sowing: { method: 'Dibbling', depth: '3-5 cm', spacing: '90x60 cm', bestTime: 'Jun 15 - Jul 15', seedRate: '2.5-3 kg/acre (Bt hybrids)' },
    harvest: { timing: '150-180 DAS', signs: 'Bolls crack open and kapas is fluffy white', method: 'Hand picking in 3-4 rounds at 15-day intervals', yield: '8-12 q/acre' },
    msp: { price: 7121, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'cotton', soilType: 'black', season: 'kharif', region: 'maharashtra',
    fertilizer: { type: 'NPK 20:20:20 + Sulphur', quantity: '50 kg/acre', schedule: 'Basal at sowing, top dress urea 25 kg/acre at 30 and 60 DAS', notes: 'Apply 2.5 tonnes FYM/acre; supplement with MgSO4 5 kg/acre for Vidarbha soils' },
    irrigation: { method: 'Furrow irrigation', frequency: 'Every 10-12 days', waterPerAcre: '400 litres/day', notes: 'Avoid waterlogging; provide drainage in heavy black soils' },
    pest: { commonPests: ['Pink Bollworm', 'Jassids', 'Thrips'], prevention: 'Seed treatment with Imidacloprid 600FS @5ml/kg seed', treatment: 'Spray Emamectin Benzoate 5% SG @4g/10L water', spraySchedule: 'Based on ETL: 5-10% fruiting body damage' },
    sowing: { method: 'Dibbling', depth: '3-5 cm', spacing: '90x60 cm for irrigated, 120x45 cm for rainfed', bestTime: 'Jun 1 - Jul 10', seedRate: '2.5 kg/acre' },
    harvest: { timing: '155-185 DAS', signs: 'Fully opened bolls with white lint', method: 'Manual picking in 3-4 rounds', yield: '6-10 q/acre (rainfed), 10-15 q/acre (irrigated)' },
    msp: { price: 7121, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'cotton', soilType: 'red', season: 'kharif', region: 'gujarat',
    fertilizer: { type: 'DAP + Urea', quantity: 'DAP 50 kg/acre basal, Urea 25 kg/acre top dress', schedule: 'DAP at sowing, Urea split at 30 and 60 DAS', notes: 'Apply ZnSO4 10 kg/acre for red soils deficient in zinc' },
    irrigation: { method: 'Drip irrigation', frequency: 'Every 4-5 days', waterPerAcre: '600 litres/day', notes: 'Red soils have low water retention; frequent light irrigation preferred' },
    pest: { commonPests: ['Whitefly', 'Mealybug', 'American Bollworm'], prevention: 'Yellow sticky traps, neem oil spray at 15 DAS', treatment: 'Spray Acetamiprid 20% SP @1g/10L for whitefly', spraySchedule: 'Scout weekly from 25 DAS onward' },
    sowing: { method: 'Dibbling', depth: '3-4 cm', spacing: '90x45 cm', bestTime: 'Jun 10 - Jul 10', seedRate: '3 kg/acre' },
    harvest: { timing: '150-175 DAS', signs: 'Bolls open with clean white kapas', method: 'Hand picking in 3 rounds', yield: '7-10 q/acre' },
    msp: { price: 7121, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'cotton', soilType: 'alluvial', season: 'kharif', region: 'rajasthan',
    fertilizer: { type: 'NPK 20:20:0 + MOP', quantity: 'NPK 50 kg/acre + MOP 20 kg/acre', schedule: 'All basal except half N as top dressing at 45 DAS', notes: 'Potassium is critical for fibre quality in alluvial soils' },
    irrigation: { method: 'Sprinkler / Flood', frequency: 'Every 8-10 days', waterPerAcre: '450 litres/day', notes: 'Avoid excess water at boll opening stage' },
    pest: { commonPests: ['Pink Bollworm', 'Spotted Bollworm', 'Aphids'], prevention: 'Crop rotation with pulses, deep summer ploughing', treatment: 'Spray Chlorantraniliprole 18.5% SC @3ml/10L water', spraySchedule: 'At square formation and peak flowering' },
    sowing: { method: 'Dibbling behind plough', depth: '4-5 cm', spacing: '100x45 cm', bestTime: 'May 15 - Jun 30', seedRate: '2.5 kg/acre' },
    harvest: { timing: '160-185 DAS', signs: 'Bolls burst fully, leaf fall begins', method: 'Manual picking', yield: '8-12 q/acre' },
    msp: { price: 7121, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'cotton', soilType: 'loamy', season: 'kharif', region: 'punjab',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 55 kg, DAP 55 kg, MOP 20 kg per acre', schedule: 'DAP and MOP full basal; Urea in 3 splits at 0, 30, 60 DAS', notes: 'Add micronutrients ZnSO4 and FeSO4 in deficient fields' },
    irrigation: { method: 'Canal / Flood irrigation', frequency: 'Every 10-14 days', waterPerAcre: '350 litres/day', notes: 'First irrigation at 3 weeks; skip at boll opening to avoid staining' },
    pest: { commonPests: ['Whitefly', 'Jassids', 'CLCuV disease'], prevention: 'Use resistant varieties (PAU Bt hybrids), avoid early planting', treatment: 'Spray Diafenthiuron 50% WP @24g/10L for whitefly', spraySchedule: 'Need-based, avoid calendar spraying' },
    sowing: { method: 'Drill sowing', depth: '4-5 cm', spacing: '67.5x75 cm', bestTime: 'Apr 15 - May 31', seedRate: '3 kg/acre' },
    harvest: { timing: '160-190 DAS', signs: 'Bolls open, 60% of bolls are mature', method: 'Machine/hand picking', yield: '10-15 q/acre' },
    msp: { price: 7121, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'cotton', soilType: 'any', season: 'any', region: 'any',
    fertilizer: { type: 'NPK 20:20:20', quantity: '50 kg/acre', schedule: 'Basal dose at sowing, nitrogen top dressing at 30 and 60 DAS', notes: 'Apply well-decomposed FYM 4-5 tonnes/acre. Soil test recommended.' },
    irrigation: { method: 'Drip / Furrow irrigation', frequency: 'Every 7-10 days depending on soil type', waterPerAcre: '400-600 litres/day', notes: 'Critical stages: square formation, flowering, boll development. Avoid waterlogging.' },
    pest: { commonPests: ['American Bollworm', 'Pink Bollworm', 'Whitefly', 'Jassids'], prevention: 'Use Bt cotton varieties, pheromone traps 5/acre, refugia border rows', treatment: 'Spray Profenofos 50% EC @2ml/L or Emamectin Benzoate 5% SG @4g/10L', spraySchedule: 'Based on ETL monitoring at weekly intervals from 30 DAS' },
    sowing: { method: 'Dibbling', depth: '3-5 cm', spacing: '90x60 cm', bestTime: 'June-July (Kharif)', seedRate: '2.5-3 kg/acre' },
    harvest: { timing: '150-180 DAS', signs: 'Bolls crack open, lint is white and fluffy', method: 'Hand picking in 3-4 rounds at 10-15 day intervals', yield: '8-12 q/acre' },
    msp: { price: 7121, unit: '₹/quintal', year: '2024-25' },
  },

  // ============================================================
  // RICE (Kharif primary, MSP 2300)
  // ============================================================
  {
    crop: 'rice', soilType: 'alluvial', season: 'kharif', region: 'telangana',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 55 kg, DAP 50 kg, MOP 25 kg per acre', schedule: 'DAP and MOP basal; Urea in 3 splits - transplanting, tillering, panicle initiation', notes: 'Apply ZnSO4 10 kg/acre in zinc-deficient fields' },
    irrigation: { method: 'Flood irrigation (puddled fields)', frequency: 'Maintain 2-5 cm standing water', waterPerAcre: '1200 litres/day', notes: 'Drain field 10 days before harvest. AWD method can save 20-30% water.' },
    pest: { commonPests: ['Stem Borer', 'Brown Planthopper', 'Blast disease'], prevention: 'Use resistant varieties (BPT-5204, RNR-15048), balanced N application', treatment: 'For BPH: Pymetrozine 50% WG @6g/10L; For Blast: Tricyclazole 75% WP @6g/10L', spraySchedule: 'Scout at tillering and panicle stages' },
    sowing: { method: 'Transplanting (nursery to main field)', depth: '2-3 cm', spacing: '20x15 cm', bestTime: 'Jun 15 - Jul 31 (nursery 25-30 days prior)', seedRate: '20 kg/acre for nursery' },
    harvest: { timing: '120-140 DAS', signs: 'Grains turn golden yellow, 80% panicles mature', method: 'Manual or combine harvester', yield: '20-25 q/acre' },
    msp: { price: 2300, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'rice', soilType: 'clay', season: 'kharif', region: 'west bengal',
    fertilizer: { type: 'Urea + SSP + MOP', quantity: 'Urea 50 kg, SSP 75 kg, MOP 20 kg per acre', schedule: 'SSP and MOP full basal; Urea split - 1/3 basal, 1/3 at active tillering, 1/3 at PI', notes: 'Apply lime 2 q/acre in acidic clay soils. Green manuring with Dhaincha improves soil.' },
    irrigation: { method: 'Flood irrigation', frequency: 'Maintain 5 cm standing water up to grain filling', waterPerAcre: '1300 litres/day', notes: 'Intermittent drying at tillering promotes root growth' },
    pest: { commonPests: ['Gall Midge', 'Leaf Folder', 'Sheath Blight'], prevention: 'Early transplanting, avoid excess nitrogen', treatment: 'Spray Chlorantraniliprole 18.5% SC @3ml/10L for stem borer/leaf folder', spraySchedule: 'At max tillering and booting stages' },
    sowing: { method: 'Transplanting', depth: '2-3 cm', spacing: '20x15 cm', bestTime: 'Jul 1 - Aug 15', seedRate: '20 kg/acre nursery' },
    harvest: { timing: '125-145 DAS', signs: 'Straw turns yellow, grain hard and firm', method: 'Manual harvesting and threshing', yield: '18-22 q/acre' },
    msp: { price: 2300, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'rice', soilType: 'loamy', season: 'kharif', region: 'punjab',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 60 kg, DAP 55 kg, MOP 25 kg per acre', schedule: 'DAP+MOP basal; Urea: 1/3 at transplanting, 1/3 at 21 DAT, 1/3 at 42 DAT', notes: 'Use LCC (Leaf Colour Chart) for N management. Apply iron chelate in alkaline soils.' },
    irrigation: { method: 'Flood / DSR alternate wetting-drying', frequency: 'Maintain 5 cm water or irrigate at hairline crack stage', waterPerAcre: '1400 litres/day', notes: 'PAU recommends DSR to save water and labour. Avoid transplanting before June 15 (state advisory).' },
    pest: { commonPests: ['Paddy Stem Borer', 'Brown Planthopper', 'Bacterial Leaf Blight'], prevention: 'Use certified seed (PR-126, Pusa-44 alternatives), balanced fertilization', treatment: 'For stem borer: Cartap Hydrochloride 4G @10 kg/acre; For BLB: Streptocycline 6g + Copper Oxychloride 500g in 200L water', spraySchedule: 'ETL-based at tillering and heading' },
    sowing: { method: 'Transplanting / DSR', depth: '2-3 cm', spacing: '20x15 cm (transplanted), rows 20 cm apart (DSR)', bestTime: 'Jun 15 - Jul 15 (state mandated)', seedRate: '8-10 kg/acre for DSR, 20 kg/acre nursery for transplant' },
    harvest: { timing: '115-135 DAS', signs: 'Grain moisture 20-22%, panicles golden', method: 'Combine harvester with Happy Seeder for residue management', yield: '25-30 q/acre' },
    msp: { price: 2300, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'rice', soilType: 'laterite', season: 'kharif', region: 'odisha',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 45 kg, DAP 40 kg, MOP 20 kg per acre', schedule: 'Half N + full P&K basal; remaining N in two equal splits at tillering and PI', notes: 'Laterite soils need lime application 4 q/acre. Add Boron 1 kg/acre.' },
    irrigation: { method: 'Rainfed with supplemental irrigation', frequency: 'Monsoon-dependent; provide life-saving irrigation at flowering if dry spell', waterPerAcre: '800 litres/day', notes: 'SRI method suitable for water-scarce laterite tracts' },
    pest: { commonPests: ['Yellow Stem Borer', 'Gall Midge', 'Rice Tungro Virus'], prevention: 'Use light traps, grow tolerant varieties (Lalat, Swarna)', treatment: 'Fipronil 5% SC @30ml/10L for stem borer; remove tungro-infected plants', spraySchedule: 'Prophylactic at 30 DAT, curative at booting if pest incidence >5%' },
    sowing: { method: 'Transplanting', depth: '2-3 cm', spacing: '20x15 cm', bestTime: 'Jul 1 - Aug 10', seedRate: '20 kg/acre' },
    harvest: { timing: '130-145 DAS', signs: 'Grain turns straw-coloured, firm on pressing', method: 'Manual sickle harvesting', yield: '15-20 q/acre' },
    msp: { price: 2300, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'rice', soilType: 'black', season: 'rabi', region: 'andhra pradesh',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 50 kg, DAP 50 kg, MOP 25 kg per acre', schedule: 'Basal P&K, N split in 3 doses', notes: 'Rabi rice in black soils - apply Gypsum 100 kg/acre for saline patches' },
    irrigation: { method: 'Canal irrigation', frequency: 'Maintain 3-5 cm water during vegetative phase', waterPerAcre: '1100 litres/day', notes: 'Rabi season has assured canal water; drain 7 days before harvest' },
    pest: { commonPests: ['Brown Planthopper', 'Neck Blast', 'False Smut'], prevention: 'Avoid excess N in rabi; use silicon-rich amendments', treatment: 'Isoprothiolane 40% EC @15ml/10L for blast; Propiconazole 25% EC @10ml/10L for false smut', spraySchedule: 'Preventive spray at booting and 50% heading' },
    sowing: { method: 'Transplanting', depth: '2-3 cm', spacing: '20x15 cm', bestTime: 'Nov 15 - Dec 31 (Rabi/Yasangi)', seedRate: '20 kg/acre' },
    harvest: { timing: '130-145 DAS (April-May)', signs: 'Grain hard, straw golden, field drying', method: 'Combine harvester', yield: '22-28 q/acre' },
    msp: { price: 2300, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'rice', soilType: 'any', season: 'any', region: 'any',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 50 kg, DAP 50 kg, MOP 25 kg per acre', schedule: 'Full P&K as basal; N in 3 equal splits at transplanting, tillering, and panicle initiation', notes: 'Get soil tested. Apply FYM 4-5 tonnes/acre. Zinc and iron may be needed.' },
    irrigation: { method: 'Flood / AWD (Alternate Wetting and Drying)', frequency: 'Maintain 2-5 cm water during critical stages', waterPerAcre: '1000-1400 litres/day', notes: 'Critical stages: transplanting establishment, tillering, flowering. Drain before harvest.' },
    pest: { commonPests: ['Stem Borer', 'Brown Planthopper', 'Blast', 'Sheath Blight'], prevention: 'Balanced N use, resistant varieties, proper spacing for air circulation', treatment: 'Cartap Hydrochloride 4G @10 kg/acre for stem borer; Tricyclazole 75% WP @6g/10L for blast', spraySchedule: 'Monitor weekly; spray at ETL thresholds - generally at tillering and heading' },
    sowing: { method: 'Transplanting / Direct Seeded Rice (DSR)', depth: '2-3 cm', spacing: '20x15 cm', bestTime: 'Kharif: Jun-Jul; Rabi: Nov-Dec', seedRate: '20 kg/acre (nursery), 8-10 kg/acre (DSR)' },
    harvest: { timing: '120-145 DAS', signs: 'Panicles droop, 80% grains golden, grain hard on biting', method: 'Manual or combine harvester', yield: '18-28 q/acre' },
    msp: { price: 2300, unit: '₹/quintal', year: '2024-25' },
  },

  // ============================================================
  // WHEAT (Rabi crop, MSP 2275)
  // ============================================================
  {
    crop: 'wheat', soilType: 'alluvial', season: 'rabi', region: 'punjab',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 65 kg, DAP 55 kg, MOP 15 kg per acre', schedule: 'Full P&K basal; N: half basal, 1/4 at CRI (21 DAS), 1/4 at tillering', notes: 'Apply ZnSO4 10 kg/acre every 3rd year' },
    irrigation: { method: 'Flood / Sprinkler', frequency: '4-6 irrigations at CRI, tillering, jointing, flowering, milking, dough stages', waterPerAcre: '250 litres/day avg', notes: 'CRI (Crown Root Initiation at 21 DAS) is most critical. Delay causes 30-40% yield loss.' },
    pest: { commonPests: ['Yellow Rust', 'Karnal Bunt', 'Aphids', 'Termites'], prevention: 'Use rust-resistant varieties (HD-3226, PBW-824), seed treatment with Tebuconazole', treatment: 'Propiconazole 25% EC @10ml/10L for rust; Imidacloprid 200SL @2ml/10L for aphids', spraySchedule: 'Rust preventive at flag leaf stage; aphid at ear emergence' },
    sowing: { method: 'Seed drill (zero-till preferred)', depth: '4-5 cm', spacing: 'Row spacing 20-22.5 cm', bestTime: 'Nov 1-25 (timely), Nov 25-Dec 15 (late)', seedRate: '40 kg/acre (timely), 50 kg/acre (late)' },
    harvest: { timing: '140-155 DAS (April)', signs: 'Grain hard, straw golden yellow, moisture <14%', method: 'Combine harvester', yield: '18-22 q/acre' },
    msp: { price: 2275, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'wheat', soilType: 'loamy', season: 'rabi', region: 'haryana',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 60 kg, DAP 50 kg, MOP 15 kg per acre', schedule: 'Full P&K + half N at sowing; remaining N at CRI and late tillering', notes: 'Haryana soils often low in organic carbon - add FYM 4 t/acre' },
    irrigation: { method: 'Flood irrigation via canal/tubewell', frequency: '5 irrigations: CRI, late tillering, late jointing, flowering, milk stage', waterPerAcre: '250 litres/day', notes: 'Sprinkler can save 20% water. Skip last irrigation if monsoon residual moisture is good.' },
    pest: { commonPests: ['Loose Smut', 'Yellow Rust', 'Pink Stem Borer'], prevention: 'Seed treatment with Carboxin + Thiram @2.5g/kg seed; timely sowing', treatment: 'Propiconazole 25% EC @10ml/10L for rust at first symptoms', spraySchedule: 'At flag leaf emergence and heading' },
    sowing: { method: 'Seed drill', depth: '4-5 cm', spacing: '20-22.5 cm row spacing', bestTime: 'Nov 5-25 (timely sown)', seedRate: '40 kg/acre' },
    harvest: { timing: '140-150 DAS', signs: 'Plants completely dry, ear golden, grain hard', method: 'Combine harvester', yield: '18-22 q/acre' },
    msp: { price: 2275, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'wheat', soilType: 'black', season: 'rabi', region: 'madhya pradesh',
    fertilizer: { type: 'DAP + Urea + MOP', quantity: 'DAP 50 kg, Urea 55 kg, MOP 10 kg per acre', schedule: 'Full P&K + 1/3 N basal; remaining N in 2 splits', notes: 'Black soils retain moisture - reduce N slightly to avoid lodging. Apply Sulphur 10 kg/acre.' },
    irrigation: { method: 'Sprinkler / Flood', frequency: '3-4 irrigations; black soils hold moisture longer', waterPerAcre: '200 litres/day', notes: 'Pre-sowing irrigation (rauni) essential. Avoid waterlogging in heavy clay.' },
    pest: { commonPests: ['Brown Rust', 'Powdery Mildew', 'Aphids'], prevention: 'Timely sowing, recommended varieties (HI-1544, MP-3336)', treatment: 'Spray Propiconazole 25% EC @10ml/10L for mildew/rust', spraySchedule: 'At first sign of disease on leaves' },
    sowing: { method: 'Seed drill after rauni', depth: '5-6 cm', spacing: '22.5 cm rows', bestTime: 'Nov 10-30', seedRate: '40-45 kg/acre' },
    harvest: { timing: '130-145 DAS', signs: 'Ears droop, straw dries completely', method: 'Manual/combine', yield: '15-20 q/acre' },
    msp: { price: 2275, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'wheat', soilType: 'sandy', season: 'rabi', region: 'rajasthan',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 50 kg, DAP 50 kg, MOP 20 kg per acre', schedule: 'Full P&K basal; N in 3 equal splits to prevent leaching in sandy soils', notes: 'Sandy soils lose nutrients fast; split N application is critical. Add FYM 5 t/acre.' },
    irrigation: { method: 'Sprinkler irrigation', frequency: '6-8 irrigations at 12-15 day intervals', waterPerAcre: '300 litres/day', notes: 'Sandy soils drain fast; more frequent, lighter irrigations needed' },
    pest: { commonPests: ['Termites', 'Aphids', 'Brown Rust'], prevention: 'Seed treatment with Chlorpyrifos 20EC @4ml/kg for termites', treatment: 'Soil drench Chlorpyrifos 20EC @4L/acre for termite; Dimethoate 30EC @10ml/10L for aphids', spraySchedule: 'Termite: at first sign; Aphids: at ear emergence' },
    sowing: { method: 'Seed drill', depth: '5-6 cm (deeper in sandy soils)', spacing: '22.5 cm rows', bestTime: 'Nov 15 - Dec 5', seedRate: '45 kg/acre' },
    harvest: { timing: '135-150 DAS', signs: 'Grain hard, straw brittle and golden', method: 'Manual or combine', yield: '12-16 q/acre' },
    msp: { price: 2275, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'wheat', soilType: 'alluvial', season: 'rabi', region: 'uttar pradesh',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 60 kg, DAP 55 kg, MOP 15 kg per acre', schedule: 'Full P&K at sowing; N: half basal, quarter at CRI, quarter at late tillering', notes: 'Indo-Gangetic alluvial soils are fertile but zinc-deficient; apply ZnSO4.' },
    irrigation: { method: 'Canal / Tubewell flood irrigation', frequency: '5-6 irrigations at critical stages', waterPerAcre: '260 litres/day', notes: 'CRI stage (21 DAS) most critical. Late sown wheat needs fewer irrigations.' },
    pest: { commonPests: ['Leaf Rust', 'Loose Smut', 'Aphids', 'Army Worm'], prevention: 'Use HD-2967, DBW-187; seed treatment mandatory', treatment: 'Propiconazole for rust, Thiamethoxam 25% WG @2g/10L for aphids', spraySchedule: 'Rust: flag leaf stage; Aphids: heading stage' },
    sowing: { method: 'Zero-till / Conventional seed drill', depth: '4-5 cm', spacing: '20-22.5 cm', bestTime: 'Nov 1-25 (timely), up to Dec 25 (very late)', seedRate: '40 kg/acre (timely), 50-60 kg/acre (late)' },
    harvest: { timing: '135-155 DAS', signs: 'Ear completely golden, grain hard on nail test', method: 'Combine harvester', yield: '18-22 q/acre' },
    msp: { price: 2275, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'wheat', soilType: 'any', season: 'any', region: 'any',
    fertilizer: { type: 'NPK balanced dose', quantity: 'N:P:K = 60:30:15 kg/acre as Urea + DAP + MOP', schedule: 'Full P&K basal; N in 2-3 splits at sowing, CRI, and tillering stages', notes: 'Soil test based nutrient management recommended. Apply FYM 4-5 tonnes/acre.' },
    irrigation: { method: 'Flood / Sprinkler irrigation', frequency: '4-6 irrigations based on soil type and rainfall', waterPerAcre: '200-300 litres/day', notes: 'CRI stage (21 DAS) most critical. Booting and grain filling also need assured water.' },
    pest: { commonPests: ['Yellow Rust', 'Brown Rust', 'Aphids', 'Termites', 'Loose Smut'], prevention: 'Seed treatment with Carboxin+Thiram, use disease-resistant varieties', treatment: 'Propiconazole 25% EC @10ml/10L for rusts; Imidacloprid for aphids', spraySchedule: 'Monitor from jointing; spray at flag leaf and heading if symptoms appear' },
    sowing: { method: 'Seed drill', depth: '4-6 cm', spacing: '20-22.5 cm row spacing', bestTime: 'November (Rabi season); late sowing up to December', seedRate: '40-50 kg/acre' },
    harvest: { timing: '135-155 DAS', signs: 'Grain hard, golden colour, straw brittle, moisture <14%', method: 'Manual or combine harvester', yield: '15-22 q/acre' },
    msp: { price: 2275, unit: '₹/quintal', year: '2024-25' },
  },

  // ============================================================
  // MAIZE (Kharif + Rabi, MSP 2225)
  // ============================================================
  {
    crop: 'maize', soilType: 'loamy', season: 'kharif', region: 'karnataka',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 55 kg, DAP 50 kg, MOP 20 kg per acre', schedule: 'Full P&K basal; N: 1/3 basal, 1/3 at knee-high, 1/3 at tasseling', notes: 'Apply ZnSO4 10 kg/acre. Maize is heavy N feeder.' },
    irrigation: { method: 'Furrow / Sprinkler', frequency: 'Every 7-10 days', waterPerAcre: '350 litres/day', notes: 'Critical stages: tasseling and grain filling. Water stress at tasseling causes 40-50% yield loss.' },
    pest: { commonPests: ['Fall Armyworm', 'Stem Borer', 'Turcicum Leaf Blight'], prevention: 'Seed treatment with Cyantraniliprole; whorl application of granules at 15 DAS', treatment: 'Spray Emamectin Benzoate 5% SG @4g/10L for FAW; Chlorantraniliprole 18.5% SC @3ml/10L', spraySchedule: 'At 10-15 DAS for early FAW; at tasseling for borer' },
    sowing: { method: 'Dibbling / Seed drill', depth: '4-5 cm', spacing: '60x20 cm', bestTime: 'Jun 15 - Jul 15', seedRate: '8 kg/acre (hybrid)' },
    harvest: { timing: '100-120 DAS', signs: 'Cob husk dries, grain hard on thumbnail test, black layer visible', method: 'Manual or mechanical cob picking', yield: '20-30 q/acre' },
    msp: { price: 2225, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'maize', soilType: 'alluvial', season: 'rabi', region: 'bihar',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 60 kg, DAP 55 kg, MOP 25 kg per acre', schedule: 'Full P&K basal; N split in 3 doses', notes: 'Rabi maize in Bihar gives higher yields than kharif. Apply Borax 4 kg/acre.' },
    irrigation: { method: 'Flood / Furrow', frequency: 'Every 10-15 days; 5-6 irrigations total', waterPerAcre: '300 litres/day', notes: 'Pre-sowing irrigation important; critical at tasseling-silking stage' },
    pest: { commonPests: ['Fall Armyworm', 'Shoot Fly', 'Maydis Leaf Blight'], prevention: 'Seed treatment, early sowing to escape shoot fly peak', treatment: 'Spray Spinetoram 11.7% SC @4.5ml/10L for FAW', spraySchedule: 'At whorl stage (20-30 DAS) and pre-tasseling' },
    sowing: { method: 'Seed drill / Ridge planting', depth: '4-5 cm', spacing: '60x20 cm', bestTime: 'Oct 20 - Nov 15', seedRate: '8 kg/acre' },
    harvest: { timing: '130-150 DAS (March-April)', signs: 'Black layer at grain base, husk dry', method: 'Manual', yield: '30-40 q/acre' },
    msp: { price: 2225, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'maize', soilType: 'red', season: 'kharif', region: 'andhra pradesh',
    fertilizer: { type: 'DAP + Urea + MOP', quantity: 'DAP 50 kg, Urea 50 kg, MOP 20 kg per acre', schedule: 'Full P&K + 1/3 N basal; remaining N at 25 DAS and 45 DAS', notes: 'Red soils are often P-deficient; adequate P is critical for root development.' },
    irrigation: { method: 'Drip / Sprinkler', frequency: 'Every 5-7 days', waterPerAcre: '350 litres/day', notes: 'Red soils dry quickly; drip saves 40% water vs flood' },
    pest: { commonPests: ['Fall Armyworm', 'Pink Stem Borer', 'Downy Mildew'], prevention: 'Use treated hybrid seeds, inter-crop with red gram', treatment: 'Chlorantraniliprole 18.5% SC @3ml/10L for FAW; Metalaxyl seed treatment for downy mildew', spraySchedule: 'FAW: 10-15 DAS; Downy mildew: seed treatment' },
    sowing: { method: 'Dibbling', depth: '3-4 cm', spacing: '60x20 cm', bestTime: 'Jun 10 - Jul 10', seedRate: '8 kg/acre' },
    harvest: { timing: '100-115 DAS', signs: 'Cob husk turns brown, grain dents', method: 'Manual cob harvesting', yield: '18-25 q/acre' },
    msp: { price: 2225, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'maize', soilType: 'black', season: 'kharif', region: 'madhya pradesh',
    fertilizer: { type: 'Urea + SSP + MOP', quantity: 'Urea 50 kg, SSP 75 kg, MOP 15 kg per acre', schedule: 'Full P&K basal; N: half basal, quarter knee-high, quarter pre-tassel', notes: 'Black soils crack in summer - apply FYM 5 t/acre to improve structure' },
    irrigation: { method: 'Furrow irrigation', frequency: 'Rainfed mostly; protective irrigation if dry spell >10 days', waterPerAcre: '300 litres/day', notes: 'Black soils hold moisture well; avoid over-irrigation to prevent root rot' },
    pest: { commonPests: ['Fall Armyworm', 'Stem Borer', 'Charcoal Rot'], prevention: 'Balanced nutrition, avoid water stress at grain filling', treatment: 'Emamectin Benzoate 5% SG @4g/10L for FAW', spraySchedule: 'At first whorl infestation sign' },
    sowing: { method: 'Seed drill', depth: '5-6 cm', spacing: '60x25 cm', bestTime: 'Jun 20 - Jul 15', seedRate: '8-10 kg/acre' },
    harvest: { timing: '105-120 DAS', signs: 'Husk dry, black layer formation on grain', method: 'Manual picking', yield: '16-22 q/acre' },
    msp: { price: 2225, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'maize', soilType: 'sandy', season: 'kharif', region: 'rajasthan',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 45 kg, DAP 45 kg, MOP 20 kg per acre', schedule: 'Split all nutrients - 2 basal, 2 top dressing to reduce leaching', notes: 'Sandy soils lose nutrients quickly. Apply FYM 6 t/acre, use neem-coated urea.' },
    irrigation: { method: 'Sprinkler', frequency: 'Every 5-6 days', waterPerAcre: '400 litres/day', notes: 'Frequent light irrigations needed in sandy soils; mulching reduces evaporation' },
    pest: { commonPests: ['Fall Armyworm', 'Shoot Fly', 'Termites'], prevention: 'Seed treatment with Fipronil for termites; early sowing', treatment: 'Thiamethoxam 12.6% + Lambda-cyhalothrin 9.5% ZC @2.5ml/10L for FAW', spraySchedule: 'At 10-12 DAS and whorl stage' },
    sowing: { method: 'Dibbling', depth: '5-7 cm', spacing: '60x20 cm', bestTime: 'Jul 1 - Jul 20', seedRate: '8-10 kg/acre' },
    harvest: { timing: '95-110 DAS', signs: 'Husk and silk dry, grain firm', method: 'Manual', yield: '12-18 q/acre' },
    msp: { price: 2225, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'maize', soilType: 'any', season: 'any', region: 'any',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 55 kg, DAP 50 kg, MOP 20 kg per acre', schedule: 'Full P&K basal; N in 3 splits: sowing, knee-high (25-30 DAS), pre-tasseling (45-50 DAS)', notes: 'Maize is a heavy N feeder. Apply FYM 5 t/acre. Zinc and Boron supplementation beneficial.' },
    irrigation: { method: 'Furrow / Sprinkler / Drip', frequency: 'Every 7-10 days depending on soil', waterPerAcre: '300-400 litres/day', notes: 'Critical: tasseling and silking stage. Water stress here reduces yield 40-50%.' },
    pest: { commonPests: ['Fall Armyworm', 'Stem Borer', 'Turcicum Leaf Blight', 'Downy Mildew'], prevention: 'Seed treatment, early sowing, pheromone traps for FAW', treatment: 'Emamectin Benzoate 5% SG @4g/10L or Chlorantraniliprole 18.5% SC @3ml/10L', spraySchedule: 'At whorl stage for FAW (10-20 DAS); at tasseling for borer' },
    sowing: { method: 'Seed drill / Dibbling', depth: '4-6 cm', spacing: '60x20 cm', bestTime: 'Kharif: Jun-Jul; Rabi: Oct-Nov; Spring: Jan-Feb', seedRate: '8-10 kg/acre (hybrid)' },
    harvest: { timing: '100-130 DAS', signs: 'Black layer on grain, husk dry, grain moisture <25%', method: 'Manual or mechanical', yield: '15-35 q/acre depending on season and management' },
    msp: { price: 2225, unit: '₹/quintal', year: '2024-25' },
  },

  // ============================================================
  // TOMATO (No MSP, market-driven)
  // ============================================================
  {
    crop: 'tomato', soilType: 'red', season: 'rabi', region: 'karnataka',
    fertilizer: { type: 'NPK 19:19:19 + Calcium Nitrate', quantity: 'NPK 50 kg/acre basal, CaNO3 25 kg/acre at fruiting', schedule: 'Basal NPK, foliar CaNO3 at fruit set, top dress Urea 20 kg at 30 and 50 DAT', notes: 'Calcium prevents blossom end rot. Apply micronutrients (B, Zn, Fe) fortnightly.' },
    irrigation: { method: 'Drip irrigation', frequency: 'Daily in summer, alternate days in rabi', waterPerAcre: '600-800 litres/day', notes: 'Mulching with black plastic reduces weeds and conserves moisture. Avoid wetting foliage.' },
    pest: { commonPests: ['Tuta absoluta', 'Fruit Borer', 'Leaf Curl Virus (ToLCV)', 'Early Blight'], prevention: 'Use ToLCV-resistant varieties, pheromone traps for Tuta, yellow sticky traps for whitefly', treatment: 'Chlorantraniliprole 18.5% SC @3ml/10L for Tuta/borer; Mancozeb 75% WP @25g/10L for blight', spraySchedule: 'Weekly from flowering to harvest' },
    sowing: { method: 'Transplanting (nursery raised)', depth: '1-2 cm nursery, transplant at soil level', spacing: '60x45 cm', bestTime: 'Sep-Oct (Rabi); Jan-Feb (Summer)', seedRate: '150-200g/acre nursery' },
    harvest: { timing: '60-75 days after transplanting', signs: 'Fruits turn red/pink, firm to touch', method: 'Manual picking every 3-5 days', yield: '100-150 q/acre (hybrid open field)' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'tomato', soilType: 'loamy', season: 'kharif', region: 'maharashtra',
    fertilizer: { type: 'DAP + MOP + Urea', quantity: 'DAP 50 kg, MOP 30 kg, Urea 40 kg per acre', schedule: 'Full P&K basal; N in 4 splits through drip fertigation', notes: 'Kharif tomato prone to diseases; avoid excess N which promotes vegetative growth over fruiting' },
    irrigation: { method: 'Drip irrigation', frequency: 'Daily 30-45 minutes', waterPerAcre: '700 litres/day', notes: 'Raised beds essential for kharif to prevent waterlogging. Mulch with straw.' },
    pest: { commonPests: ['Fruit Borer', 'Whitefly', 'Late Blight', 'Bacterial Wilt'], prevention: 'Raised beds, crop rotation with non-solanaceous crops, Trichoderma soil application', treatment: 'Indoxacarb 14.5% SC @6ml/10L for borer; Cymoxanil+Mancozeb for late blight', spraySchedule: 'Preventive fungicide every 10 days in rainy season' },
    sowing: { method: 'Transplanting on raised beds', depth: 'Collar region at soil level', spacing: '75x60 cm on beds', bestTime: 'Jun-Jul (Kharif)', seedRate: '150g/acre' },
    harvest: { timing: '65-80 DAT', signs: 'Breaker to pink stage for distant markets, fully ripe for local', method: 'Hand picking in 5-8 rounds', yield: '80-120 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'tomato', soilType: 'black', season: 'rabi', region: 'telangana',
    fertilizer: { type: 'NPK 12:32:16 + Urea', quantity: 'NPK 50 kg basal, Urea 25 kg in 3 splits', schedule: 'Basal complex at transplanting; Urea at 20, 40, 60 DAT', notes: 'Black soils have high P retention; apply extra P. Foliar spray 19:19:19 at flowering.' },
    irrigation: { method: 'Drip irrigation', frequency: 'Every 2-3 days', waterPerAcre: '600 litres/day', notes: 'Black soils crack - mulching is essential. Avoid overhead irrigation.' },
    pest: { commonPests: ['Tuta absoluta', 'Tomato Leaf Curl Virus', 'Early Blight', 'Nematodes'], prevention: 'Nematode-free transplants, neem cake 100 kg/acre in soil, resistant hybrids', treatment: 'Cyantraniliprole 10.26% OD @6ml/10L for Tuta; Carbendazim 50% WP @10g/10L for wilt', spraySchedule: 'Bi-weekly spraying from 15 DAT to last picking' },
    sowing: { method: 'Transplanting', depth: 'Crown at soil level', spacing: '60x45 cm', bestTime: 'Oct-Nov', seedRate: '150-200g/acre' },
    harvest: { timing: '60-75 DAT', signs: 'Colour break stage for transport, full red for local sale', method: 'Manual harvesting every 4-5 days', yield: '100-160 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'tomato', soilType: 'alluvial', season: 'zaid', region: 'uttar pradesh',
    fertilizer: { type: 'Urea + DAP + MOP + CaNO3', quantity: 'DAP 45 kg, MOP 25 kg, Urea 40 kg, CaNO3 20 kg per acre', schedule: 'P&K basal; N weekly through fertigation; CaNO3 at fruiting', notes: 'Summer tomato needs more K for heat tolerance. Apply Boron @1 kg/acre.' },
    irrigation: { method: 'Drip irrigation', frequency: 'Twice daily in peak summer', waterPerAcre: '900 litres/day', notes: 'Mulching absolutely essential in summer. Shade net (35%) improves fruit quality.' },
    pest: { commonPests: ['Fruit Borer', 'Mites', 'Leaf Curl Virus', 'Fusarium Wilt'], prevention: 'Heat-tolerant varieties, grafting on wilt-resistant rootstock', treatment: 'Abamectin 1.8% EC @5ml/10L for mites; Thiamethoxam 25% WG @3g/10L for whitefly/virus vector', spraySchedule: 'Weekly preventive spray in summer' },
    sowing: { method: 'Transplanting', depth: 'Crown at surface', spacing: '60x45 cm', bestTime: 'Feb-Mar (Zaid/Summer)', seedRate: '150g/acre' },
    harvest: { timing: '55-70 DAT (May-June)', signs: 'Mature green to breaker stage for summer transport', method: 'Early morning harvest to avoid heat damage', yield: '80-120 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'tomato', soilType: 'sandy', season: 'rabi', region: 'rajasthan',
    fertilizer: { type: 'NPK 19:19:19 + Urea + MOP', quantity: '50 kg NPK basal, Urea 30 kg, MOP 20 kg in splits', schedule: 'Frequent light fertigation through drip - weekly N and K doses', notes: 'Sandy soils lose nutrients fast; fertigation is the only viable option' },
    irrigation: { method: 'Drip irrigation', frequency: 'Daily', waterPerAcre: '700 litres/day', notes: 'Sandy soils drain rapidly; daily drip essential. Plastic mulch conserves 30% water.' },
    pest: { commonPests: ['Fruit Borer', 'Leaf Miner', 'Powdery Mildew'], prevention: 'Neem oil spray @5ml/L fortnightly, proper spacing for air flow', treatment: 'Spinosad 45% SC @3ml/10L for borer/leaf miner', spraySchedule: 'At flowering onset and every 10 days during fruiting' },
    sowing: { method: 'Transplanting on raised beds', depth: 'Crown at soil level', spacing: '60x45 cm', bestTime: 'Oct-Nov', seedRate: '150g/acre' },
    harvest: { timing: '60-75 DAT', signs: 'Colour change from green to pink, firm texture', method: 'Hand picking', yield: '80-110 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'tomato', soilType: 'any', season: 'any', region: 'any',
    fertilizer: { type: 'NPK 19:19:19 + Urea + Calcium Nitrate', quantity: '50 kg NPK basal, Urea 30-40 kg, CaNO3 25 kg per acre', schedule: 'Basal P&K, nitrogen in weekly splits through fertigation, calcium at fruiting', notes: 'Tomato is a heavy feeder. Apply FYM 5 t/acre. Micronutrients (B, Zn, Fe, Mn) essential.' },
    irrigation: { method: 'Drip irrigation (strongly recommended)', frequency: 'Daily to alternate days depending on season', waterPerAcre: '600-900 litres/day', notes: 'Avoid overhead watering. Mulching reduces disease incidence and water use by 30%.' },
    pest: { commonPests: ['Tuta absoluta', 'Fruit Borer', 'Whitefly', 'Leaf Curl Virus', 'Early Blight', 'Late Blight'], prevention: 'Resistant varieties, yellow/blue sticky traps, pheromone traps, crop rotation', treatment: 'Chlorantraniliprole 18.5% SC @3ml/10L for borers; Mancozeb 75% WP for fungal diseases', spraySchedule: 'Bi-weekly from transplanting; weekly during fruiting and rainy periods' },
    sowing: { method: 'Transplanting (nursery-raised seedlings)', depth: '1-2 cm in nursery; transplant at crown level', spacing: '60x45 cm to 75x60 cm', bestTime: 'Kharif: Jun-Jul; Rabi: Sep-Nov; Summer: Feb-Mar', seedRate: '150-200g/acre (nursery)' },
    harvest: { timing: '60-80 DAT, continues for 2-3 months', signs: 'Colour break stage (green to pink) for transport; fully ripe for local market', method: 'Manual picking every 3-5 days for 6-10 rounds', yield: '80-160 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },

  // ============================================================
  // GROUNDNUT (Kharif, MSP 6783)
  // ============================================================
  {
    crop: 'groundnut', soilType: 'red', season: 'kharif', region: 'andhra pradesh',
    fertilizer: { type: 'SSP + Gypsum', quantity: 'SSP 75 kg/acre basal, Gypsum 100 kg/acre at pegging', schedule: 'Full P as SSP (provides S too), Gypsum at 40-45 DAS for pod filling', notes: 'Groundnut fixes nitrogen; minimal N needed (10 kg/acre starter dose). Calcium from gypsum is critical.' },
    irrigation: { method: 'Sprinkler / Furrow', frequency: 'Every 7-10 days', waterPerAcre: '350 litres/day', notes: 'Critical: pegging and pod development (40-80 DAS). Excess water causes collar rot.' },
    pest: { commonPests: ['Leaf Miner', 'Spodoptera', 'Tikka Disease (Leaf Spot)', 'Stem Rot'], prevention: 'Seed treatment with Thiram + Carbendazim @3g/kg; crop rotation', treatment: 'Chlorothalonil 75% WP @20g/10L for leaf spots; Quinalphos 25EC @20ml/10L for pests', spraySchedule: 'Tikka: at 30 and 45 DAS; Pests: need-based' },
    sowing: { method: 'Ridge and furrow / Flat bed', depth: '5-7 cm', spacing: '30x10 cm (bunch type), 45x15 cm (spreading)', bestTime: 'Jun 15 - Jul 15', seedRate: '50-60 kg/acre (kernels)' },
    harvest: { timing: '100-120 DAS', signs: 'Leaves turn yellow, inner shell darkens, kernel fills fully', method: 'Pulling/digging followed by drying', yield: '8-12 q/acre (pod)' },
    msp: { price: 6783, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'groundnut', soilType: 'sandy', season: 'kharif', region: 'gujarat',
    fertilizer: { type: 'SSP + Gypsum + FYM', quantity: 'SSP 75 kg, Gypsum 100 kg per acre', schedule: 'SSP at sowing, Gypsum at flowering/pegging', notes: 'Sandy soils in Saurashtra ideal for groundnut. Apply FYM 4 t/acre. Sulphur-rich SSP preferred.' },
    irrigation: { method: 'Sprinkler', frequency: 'Every 5-7 days', waterPerAcre: '400 litres/day', notes: 'Sandy soils drain fast; frequent light irrigations. Avoid water at maturity.' },
    pest: { commonPests: ['White Grub', 'Leaf Miner', 'Rust', 'Collar Rot'], prevention: 'Deep ploughing for white grub; seed treatment with Mancozeb + Carbendazim', treatment: 'Hexaconazole 5% EC @10ml/10L for rust; Chlorpyrifos soil drench for white grub', spraySchedule: 'Preventive at 30-35 DAS; curative at first symptoms' },
    sowing: { method: 'Behind plough / Seed drill', depth: '5-6 cm', spacing: '30x10 cm', bestTime: 'Jun 15 - Jul 10 (with monsoon onset)', seedRate: '50 kg/acre' },
    harvest: { timing: '105-115 DAS', signs: 'Network of veins visible inside shell, kernel fills 75-80%', method: 'Manual pulling when soil is moist', yield: '8-14 q/acre' },
    msp: { price: 6783, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'groundnut', soilType: 'loamy', season: 'kharif', region: 'rajasthan',
    fertilizer: { type: 'SSP + Gypsum', quantity: 'SSP 75 kg/acre, Gypsum 80 kg/acre', schedule: 'SSP at sowing, Gypsum at pegging stage', notes: 'Loamy soils in Rajasthan produce good quality groundnut. Minimal N needed due to Rhizobium fixation.' },
    irrigation: { method: 'Sprinkler', frequency: 'Every 8-10 days', waterPerAcre: '350 litres/day', notes: 'Supplement monsoon rainfall; protective irrigation critical during dry spells at pegging' },
    pest: { commonPests: ['Aphids', 'Thrips', 'Leaf Spot', 'Root Rot'], prevention: 'Rhizobium + PSB seed inoculation, crop rotation with cereals', treatment: 'Dimethoate 30EC @10ml/10L for sucking pests; Mancozeb for leaf spot', spraySchedule: 'At 30 DAS and 50 DAS' },
    sowing: { method: 'Dibbling', depth: '5-6 cm', spacing: '30x10 cm', bestTime: 'Jul 1 - Jul 15', seedRate: '50 kg/acre' },
    harvest: { timing: '110-120 DAS', signs: 'Yellowing of foliage, inner shell dark, kernel full', method: 'Manual digging', yield: '7-10 q/acre' },
    msp: { price: 6783, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'groundnut', soilType: 'black', season: 'kharif', region: 'maharashtra',
    fertilizer: { type: 'SSP + Gypsum', quantity: 'SSP 60 kg/acre, Gypsum 100 kg/acre', schedule: 'SSP basal, Gypsum at 40-45 DAS', notes: 'Black soils can cause waterlogging; raised bed planting recommended. Calcium from gypsum improves pod quality.' },
    irrigation: { method: 'Furrow on raised beds', frequency: 'Every 10-12 days, rainfed mostly', waterPerAcre: '300 litres/day', notes: 'Provide drainage in heavy black soils; ridge planting essential' },
    pest: { commonPests: ['Spodoptera', 'Tikka Disease', 'Stem Rot', 'Aflatoxin risk'], prevention: 'Avoid waterlogging (aflatoxin risk), Trichoderma soil treatment, seed treatment', treatment: 'Chlorothalonil for leaf diseases; NSKE 5% for Spodoptera in early stages', spraySchedule: 'At 30 DAS (preventive); need-based thereafter' },
    sowing: { method: 'Ridge planting on raised beds', depth: '5-7 cm', spacing: '30x10 cm on ridges', bestTime: 'Jun 15 - Jul 10', seedRate: '55 kg/acre' },
    harvest: { timing: '105-115 DAS', signs: 'Leaves yellow, shell firm, kernel developed', method: 'Digging with blade harrow when soil moist', yield: '7-10 q/acre' },
    msp: { price: 6783, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'groundnut', soilType: 'red', season: 'rabi', region: 'tamil nadu',
    fertilizer: { type: 'SSP + Gypsum + MOP', quantity: 'SSP 75 kg, MOP 20 kg basal; Gypsum 100 kg at pegging', schedule: 'All basal except gypsum at pegging', notes: 'Rabi groundnut in TN: irrigated conditions, apply Rhizobium inoculant to seed' },
    irrigation: { method: 'Drip / Furrow', frequency: 'Every 5-7 days', waterPerAcre: '400 litres/day', notes: 'Rabi season needs assured irrigation; critical at pegging and pod development' },
    pest: { commonPests: ['Red Hairy Caterpillar', 'Leaf Spot', 'Rust', 'Bud Necrosis'], prevention: 'Light traps for caterpillar moth, Imidacloprid seed treatment for thrips (bud necrosis vector)', treatment: 'Mancozeb+Carbendazim combo for rust+leaf spot', spraySchedule: 'Fortnightly from 30 DAS' },
    sowing: { method: 'Seed drill / Dibbling', depth: '5 cm', spacing: '30x10 cm', bestTime: 'Dec 15 - Jan 15', seedRate: '55 kg/acre' },
    harvest: { timing: '100-110 DAS', signs: 'Mature pod shell shows veins, leaves dry', method: 'Blade harrow digging', yield: '10-14 q/acre (irrigated rabi gives good yields)' },
    msp: { price: 6783, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'groundnut', soilType: 'any', season: 'any', region: 'any',
    fertilizer: { type: 'SSP + Gypsum', quantity: 'SSP 75 kg/acre basal, Gypsum 100 kg/acre at pegging (40-45 DAS)', schedule: 'P and S as SSP at sowing; Calcium as gypsum at pegging; minimal N (Rhizobium inoculation)', notes: 'Groundnut is a legume - fixes nitrogen. Calcium and Sulphur are most critical nutrients. Apply FYM 4-5 t/acre.' },
    irrigation: { method: 'Sprinkler / Furrow', frequency: 'Every 7-10 days', waterPerAcre: '300-400 litres/day', notes: 'Critical: pegging, pod development (40-80 DAS). Avoid excess water (collar rot, aflatoxin risk).' },
    pest: { commonPests: ['Leaf Miner', 'Spodoptera', 'Tikka Disease', 'Rust', 'Collar Rot', 'White Grub'], prevention: 'Seed treatment with fungicide, crop rotation, Rhizobium inoculation, deep summer ploughing', treatment: 'Chlorothalonil 75% WP @20g/10L for leaf diseases; Quinalphos 25EC for insect pests', spraySchedule: 'Preventive at 30-35 DAS; repeat at 50-60 DAS if disease persists' },
    sowing: { method: 'Dibbling / Seed drill', depth: '5-7 cm', spacing: '30x10 cm (bunch), 45x15 cm (spreading)', bestTime: 'Kharif: Jun-Jul; Rabi: Dec-Jan; Summer: Feb-Mar', seedRate: '50-60 kg/acre (shelled kernels)' },
    harvest: { timing: '100-120 DAS', signs: 'Leaves yellow, inner shell darkens, kernel fills 75-80%', method: 'Pulling/digging when soil is moist; sun dry for 3-4 days', yield: '8-14 q/acre (pod)' },
    msp: { price: 6783, unit: '₹/quintal', year: '2024-25' },
  },

  // ============================================================
  // SOYBEAN (Kharif, MSP 4892)
  // ============================================================
  {
    crop: 'soybean', soilType: 'black', season: 'kharif', region: 'madhya pradesh',
    fertilizer: { type: 'DAP + SSP', quantity: 'DAP 40 kg/acre or SSP 100 kg/acre', schedule: 'Full dose as basal; Rhizobium seed inoculation for N fixation', notes: 'Soybean fixes N; P and S are critical. MP is largest soybean producer - follow ICAR-IISR recommendations.' },
    irrigation: { method: 'Rainfed (kharif crop)', frequency: 'Protective irrigation if dry spell >15 days at flowering/pod filling', waterPerAcre: '250 litres/day (when needed)', notes: 'Kharif soybean is mostly rainfed; ensure good drainage in black soils' },
    pest: { commonPests: ['Blue Beetle', 'Girdle Beetle', 'Yellow Mosaic Virus', 'Stem Fly'], prevention: 'Seed treatment with Thiamethoxam 30FS @10ml/kg; timely sowing', treatment: 'Triazophos 40EC @12ml/10L for girdle beetle; Propargite for mites', spraySchedule: 'At 25-30 DAS and at pod formation' },
    sowing: { method: 'Seed drill / Planker', depth: '3-4 cm', spacing: '45x5 cm (30 plants/sqm)', bestTime: 'Jun 20 - Jul 10 (with monsoon onset)', seedRate: '30 kg/acre' },
    harvest: { timing: '90-110 DAS (Oct)', signs: 'Leaves drop, pods turn brown, seeds rattle in pod', method: 'Sickle cutting when 90% pods brown; thresh after drying', yield: '8-12 q/acre' },
    msp: { price: 4892, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'soybean', soilType: 'loamy', season: 'kharif', region: 'maharashtra',
    fertilizer: { type: 'DAP + Sulphur', quantity: 'DAP 40 kg/acre + Sulphur 10 kg/acre', schedule: 'All basal at sowing', notes: 'Loamy soils in Vidarbha/Marathwada suit soybean well. Apply FYM 3 t/acre. Use PSB inoculant.' },
    irrigation: { method: 'Rainfed', frequency: 'Supplemental at flowering if drought', waterPerAcre: '200 litres/day (protective only)', notes: 'Mostly rainfed kharif crop; BBF (Broad Bed Furrow) for drainage in heavy rainfall areas' },
    pest: { commonPests: ['Spodoptera', 'Stem Fly', 'Anthracnose', 'Rust'], prevention: 'Deep ploughing, use recommended varieties (JS-335, MACS-1407)', treatment: 'Profenofos 50EC @10ml/10L for Spodoptera; Hexaconazole for rust', spraySchedule: 'At flowering and pod filling stages' },
    sowing: { method: 'Seed drill on BBF', depth: '3-4 cm', spacing: '45x5 cm', bestTime: 'Jun 15 - Jul 5', seedRate: '30 kg/acre' },
    harvest: { timing: '95-110 DAS', signs: '80% pods brown, leaves shed, seeds hard', method: 'Manual cutting + threshing', yield: '7-10 q/acre' },
    msp: { price: 4892, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'soybean', soilType: 'red', season: 'kharif', region: 'rajasthan',
    fertilizer: { type: 'SSP + Rhizobium', quantity: 'SSP 100 kg/acre', schedule: 'Full SSP basal; seed inoculation with Rhizobium japonicum', notes: 'Red soils in SE Rajasthan: apply lime if pH < 6.0. SSP provides both P and S.' },
    irrigation: { method: 'Sprinkler (if available)', frequency: 'Protective irrigation at flowering if needed', waterPerAcre: '250 litres/day', notes: 'Largely rainfed; one protective irrigation at R3-R5 stage greatly improves yield' },
    pest: { commonPests: ['Girdle Beetle', 'Green Semilooper', 'Bacterial Pustule'], prevention: 'Seed treatment, inter-cropping with maize (1:2 ratio)', treatment: 'Lambda-cyhalothrin 5% EC @5ml/10L for defoliators', spraySchedule: 'At 30 DAS and pod formation' },
    sowing: { method: 'Seed drill', depth: '3-5 cm', spacing: '40x5 cm', bestTime: 'Jun 25 - Jul 10', seedRate: '30 kg/acre' },
    harvest: { timing: '95-105 DAS', signs: 'Pods rattle, leaves dropped', method: 'Manual harvest', yield: '6-9 q/acre' },
    msp: { price: 4892, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'soybean', soilType: 'alluvial', season: 'kharif', region: 'uttar pradesh',
    fertilizer: { type: 'DAP + MOP', quantity: 'DAP 40 kg, MOP 10 kg per acre', schedule: 'Full basal application', notes: 'UP is emerging soybean area. Use Rhizobium + PSB for best results. Apply Zn if deficient.' },
    irrigation: { method: 'Flood / Sprinkler', frequency: 'Need-based; 1-2 irrigations if dry spell at R3-R5', waterPerAcre: '250 litres/day', notes: 'Good drainage essential; soybean does not tolerate waterlogging >48 hours' },
    pest: { commonPests: ['Leaf Folder', 'White Fly', 'Yellow Mosaic Virus', 'Charcoal Rot'], prevention: 'YMV-resistant varieties, proper seed rate to avoid dense canopy', treatment: 'Thiamethoxam 25WG @3g/10L for whitefly; destroy YMV-infected plants', spraySchedule: 'At 20-25 DAS and at flowering' },
    sowing: { method: 'Seed drill', depth: '3-4 cm', spacing: '45x5 cm', bestTime: 'Jun 20 - Jul 5', seedRate: '30 kg/acre' },
    harvest: { timing: '90-105 DAS', signs: 'Pods brown, leaves fallen, grain moisture <13%', method: 'Sickle cutting + mechanical threshing', yield: '7-10 q/acre' },
    msp: { price: 4892, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'soybean', soilType: 'clay', season: 'kharif', region: 'telangana',
    fertilizer: { type: 'DAP + Gypsum', quantity: 'DAP 40 kg, Gypsum 50 kg per acre', schedule: 'DAP basal; Gypsum at sowing for S supply', notes: 'Clay soils need good tilth before sowing. Apply Trichoderma for soil health.' },
    irrigation: { method: 'Rainfed with drainage', frequency: 'Protective only during prolonged dry spells', waterPerAcre: '200 litres/day', notes: 'Clay soils retain too much water - BBF planting and drainage channels mandatory' },
    pest: { commonPests: ['Tobacco Caterpillar', 'Stem Fly', 'Root Rot', 'Pod Blight'], prevention: 'Seed treatment with Carboxin+Thiram, avoid continuous soybean cropping', treatment: 'Chlorpyrifos 20EC @10ml/10L for soil insects; NSKE 5% for caterpillar', spraySchedule: 'At 20-25 DAS and at R3 stage' },
    sowing: { method: 'Seed drill on raised beds', depth: '3-4 cm', spacing: '45x5 cm', bestTime: 'Jun 15 - Jul 5', seedRate: '30-35 kg/acre' },
    harvest: { timing: '95-110 DAS', signs: 'All leaves dropped, pods dry and brown', method: 'Manual cutting followed by sun drying and threshing', yield: '6-9 q/acre' },
    msp: { price: 4892, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'soybean', soilType: 'any', season: 'any', region: 'any',
    fertilizer: { type: 'DAP / SSP + Rhizobium inoculant', quantity: 'DAP 40 kg/acre or SSP 100 kg/acre', schedule: 'Full P as basal at sowing; Rhizobium + PSB seed inoculation for N and P', notes: 'Soybean fixes its own N via Rhizobium. Focus on P, S, and micronutrients. Apply FYM 3-4 t/acre.' },
    irrigation: { method: 'Rainfed (kharif) / Sprinkler if available', frequency: 'Protective irrigation at flowering and pod filling during dry spells', waterPerAcre: '200-300 litres/day (when irrigated)', notes: 'Soybean cannot tolerate waterlogging. Good drainage essential. BBF recommended.' },
    pest: { commonPests: ['Girdle Beetle', 'Stem Fly', 'Spodoptera', 'Yellow Mosaic Virus', 'Rust', 'Anthracnose'], prevention: 'Seed treatment, timely sowing, recommended varieties, crop rotation', treatment: 'Triazophos 40EC @12ml/10L for beetles; Hexaconazole for rust; destroy YMV plants', spraySchedule: 'Monitor from 20 DAS; spray at ETL - typically 30 DAS and pod formation' },
    sowing: { method: 'Seed drill', depth: '3-5 cm', spacing: '45x5 cm', bestTime: 'June-July (Kharif) with onset of monsoon', seedRate: '30 kg/acre' },
    harvest: { timing: '90-110 DAS', signs: 'Leaves shed, pods turn brown, seeds rattle in pods, grain moisture <13%', method: 'Cut at ground level when 95% pods brown; dry 2-3 days then thresh', yield: '6-12 q/acre' },
    msp: { price: 4892, unit: '₹/quintal', year: '2024-25' },
  },

  // ============================================================
  // SUGARCANE (Annual, MSP/FRP 315)
  // ============================================================
  {
    crop: 'sugarcane', soilType: 'alluvial', season: 'rabi', region: 'uttar pradesh',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 130 kg, DAP 75 kg, MOP 40 kg per acre', schedule: 'Full P&K basal; N in 4 splits: planting, 30, 60, 90 DAP', notes: 'Heaviest feeder crop. Apply FYM 10 t/acre. Press mud 5 t/acre if available. UP is top producer.' },
    irrigation: { method: 'Furrow irrigation', frequency: 'Every 7-10 days in summer, 15-20 days in winter', waterPerAcre: '1500 litres/day', notes: 'Most water-intensive crop. 35-40 irrigations in 10-12 month cycle. Drip saves 40% water.' },
    pest: { commonPests: ['Top Borer', 'Early Shoot Borer', 'Red Rot', 'Smut'], prevention: 'Use disease-free setts, sett treatment with Carbendazim, detrash at 150 DAS', treatment: 'Fipronil 0.3G @10 kg/acre in soil for borers; remove and burn red rot infected clumps', spraySchedule: 'Granular application at 30, 60, 90 DAP for borers' },
    sowing: { method: 'Sett planting in furrows (3-bud setts)', depth: '10-15 cm furrow depth', spacing: '75-90 cm row spacing', bestTime: 'Feb-Mar (spring planting), Oct (autumn planting)', seedRate: '25,000-30,000 setts/acre (3-bud)' },
    harvest: { timing: '10-12 months after planting', signs: 'Brix >18%, pol >14%, hand refractometer reading', method: 'Manual cutting at ground level; avoid topping green top', yield: '300-400 q/acre' },
    msp: { price: 315, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'sugarcane', soilType: 'black', season: 'kharif', region: 'maharashtra',
    fertilizer: { type: 'Urea + SSP + MOP', quantity: 'Urea 120 kg, SSP 150 kg, MOP 40 kg per acre', schedule: 'P&K basal; N in 4 splits over first 4 months', notes: 'Maharashtra - Adsali (pre-seasonal) and Suru planting systems. Apply Pressmud 10 t/acre.' },
    irrigation: { method: 'Drip irrigation (VSI recommendation)', frequency: 'Daily through drip', waterPerAcre: '1200 litres/day (drip)', notes: 'Maharashtra promotes drip for sugarcane - subsidy available under PMKSY. Saves 50% water.' },
    pest: { commonPests: ['Internode Borer', 'Woolly Aphid', 'Red Rot', 'Wilt'], prevention: 'Healthy sett selection, hot water treatment 50°C for 2 hrs, resistant varieties', treatment: 'Release Trichogramma @50,000/acre for borers; Imidacloprid for woolly aphid', spraySchedule: 'Trichogramma release 4-5 times at 15-day intervals from 4th month' },
    sowing: { method: 'Sett planting in furrows', depth: '10-15 cm', spacing: '120-150 cm (paired row trench)', bestTime: 'Oct-Nov (Adsali/Pre-seasonal), Jan-Feb (Suru)', seedRate: '20,000-25,000 setts/acre' },
    harvest: { timing: '12-14 months (Adsali gives 16-18 months)', signs: 'Brix >20%, maturity coefficient >0.85', method: 'Manual cutting', yield: '400-500 q/acre (Adsali); 300-400 q/acre (Suru)' },
    msp: { price: 315, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'sugarcane', soilType: 'loamy', season: 'rabi', region: 'karnataka',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 110 kg, DAP 65 kg, MOP 40 kg per acre', schedule: 'P&K full basal; N in 3-4 equal splits up to 90 DAP', notes: 'Karnataka north zone is a major sugarcane belt. Apply FYM 8-10 t/acre.' },
    irrigation: { method: 'Drip / Furrow', frequency: 'Drip daily; Furrow every 8-10 days', waterPerAcre: '1300 litres/day', notes: 'Subsurface drip gives best results. Earthing up at 60 and 120 DAP.' },
    pest: { commonPests: ['Early Shoot Borer', 'Pyrilla', 'Grassy Shoot Disease'], prevention: 'Remove and destroy dead hearts, use healthy seed material', treatment: 'Phorate 10G @6 kg/acre at 30 DAP for borers; conserve Epiricania (natural enemy of Pyrilla)', spraySchedule: 'Granular at 30 and 60 DAP' },
    sowing: { method: 'Sett planting in furrows', depth: '10-12 cm', spacing: '90 cm rows', bestTime: 'Jan-Feb', seedRate: '25,000 setts/acre' },
    harvest: { timing: '11-12 months', signs: 'Brix readings >18%, cane starts flowering', method: 'Manual cutting at base', yield: '350-450 q/acre' },
    msp: { price: 315, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'sugarcane', soilType: 'clay', season: 'kharif', region: 'tamil nadu',
    fertilizer: { type: 'Urea + SSP + MOP', quantity: 'Urea 100 kg, SSP 125 kg, MOP 35 kg per acre', schedule: 'P&K basal; N in 3 splits up to 90 DAP; avoid N after grand growth', notes: 'TN practices settling planting with chip buds. Silicon application improves lodging resistance.' },
    irrigation: { method: 'Drip / Flood', frequency: 'Every 7 days flood; daily drip', waterPerAcre: '1400 litres/day', notes: 'Clay soils need careful water management; avoid waterlogging in early stage' },
    pest: { commonPests: ['Internode Borer', 'Scale Insect', 'Smut', 'Red Rot'], prevention: 'Disease-free seed, moist hot air treatment, varietal resistance', treatment: 'Carbofuran 3G @12 kg/acre for borers; rogue out smut-affected clumps', spraySchedule: 'Granular at 45 and 90 DAP' },
    sowing: { method: 'Single-bud chip bud settlings', depth: '8-10 cm', spacing: '150 cm (wide row) or 90 cm (normal)', bestTime: 'Dec-Jan (main season)', seedRate: '15,000-20,000 settlings/acre' },
    harvest: { timing: '11-12 months', signs: 'Juice brix >20%, reducing sugars low', method: 'Manual harvest', yield: '350-450 q/acre' },
    msp: { price: 315, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'sugarcane', soilType: 'red', season: 'rabi', region: 'andhra pradesh',
    fertilizer: { type: 'Urea + DAP + MOP + Sulphur', quantity: 'Urea 110 kg, DAP 60 kg, MOP 35 kg, Sulphur 10 kg per acre', schedule: 'P&K&S basal; N in 4 splits', notes: 'Red soils in AP coastal belt: apply FYM 8 t/acre and vermicompost 2 t/acre' },
    irrigation: { method: 'Drip / Furrow', frequency: 'Every 5-7 days', waterPerAcre: '1200 litres/day', notes: 'Red soils drain faster; more frequent, moderate irrigation. Mulch with trash.' },
    pest: { commonPests: ['Top Borer', 'White Fly', 'Pokkah Boeng', 'Wilt'], prevention: 'Resistant varieties (Co 86032, CoA 92081), healthy sett selection', treatment: 'Monocrotophos 36SL @12ml/10L for whitefly; Propiconazole for Pokkah Boeng', spraySchedule: 'At 30-45 DAP and at tillering peak' },
    sowing: { method: 'Sett planting in furrows', depth: '10-12 cm', spacing: '90-100 cm', bestTime: 'Jan-Feb (spring)', seedRate: '25,000 setts/acre' },
    harvest: { timing: '11-12 months', signs: 'Brix >18%, mature internodes develop wax', method: 'Manual cutting', yield: '300-400 q/acre' },
    msp: { price: 315, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'sugarcane', soilType: 'any', season: 'any', region: 'any',
    fertilizer: { type: 'Urea + DAP + MOP', quantity: 'Urea 110-130 kg, DAP 65-75 kg, MOP 35-40 kg per acre', schedule: 'Full P&K basal; N in 4 equal splits at planting, 30, 60, 90 DAP. No N after 120 DAP.', notes: 'Heaviest nutrient demanding crop. Apply FYM 8-10 t/acre. Press mud, filter cake, or compost beneficial.' },
    irrigation: { method: 'Drip (recommended) / Furrow irrigation', frequency: 'Daily (drip) or every 7-10 days (furrow)', waterPerAcre: '1200-1500 litres/day', notes: 'Needs 35-40 irrigations in crop cycle. Critical: germination, tillering, grand growth. Reduce water 30 days before harvest.' },
    pest: { commonPests: ['Early Shoot Borer', 'Top Borer', 'Internode Borer', 'Red Rot', 'Smut', 'Wilt'], prevention: 'Disease-free setts, hot water sett treatment (50°C/2hr), Trichoderma application, detrashing', treatment: 'Phorate/Carbofuran granules for borers; rogue diseased clumps for red rot/smut', spraySchedule: 'Granular insecticide at 30, 60, 90 DAP; Trichogramma release from 4th month' },
    sowing: { method: 'Sett planting (2-3 bud setts) in furrows', depth: '10-15 cm furrow', spacing: '75-150 cm depending on system', bestTime: 'Spring: Jan-Mar; Autumn: Oct-Nov; Adsali: Jul-Aug', seedRate: '20,000-30,000 setts/acre' },
    harvest: { timing: '10-14 months depending on variety and planting season', signs: 'Brix >18%, juice maturity coefficient >0.85, wax formation on internodes', method: 'Manual cutting at ground level; send to mill within 24 hours', yield: '300-500 q/acre' },
    msp: { price: 315, unit: '₹/quintal', year: '2024-25' },
  },

  // ============================================================
  // ONION (Rabi primary, no MSP)
  // ============================================================
  {
    crop: 'onion', soilType: 'red', season: 'rabi', region: 'maharashtra',
    fertilizer: { type: 'DAP + MOP + Urea + Sulphur', quantity: 'DAP 50 kg, MOP 25 kg, Urea 40 kg, Sulphur 10 kg per acre', schedule: 'Full P&K&S basal; N in 3 splits at transplanting, 30, 45 DAT', notes: 'Nashik/Pune belt is onion capital. Sulphur enhances pungency and storage quality.' },
    irrigation: { method: 'Drip / Sprinkler', frequency: 'Every 3-5 days', waterPerAcre: '350 litres/day', notes: 'Stop irrigation 10-15 days before harvest for better storage. Avoid waterlogging.' },
    pest: { commonPests: ['Thrips', 'Purple Blotch', 'Stemphylium Blight', 'Basal Rot'], prevention: 'Raised bed planting, proper spacing, Trichoderma soil treatment, mulching', treatment: 'Fipronil 5% SC @15ml/10L for thrips; Mancozeb 75WP @25g/10L + Carbendazim 50WP @10g/10L for fungal diseases', spraySchedule: 'Thrips: from 30 DAT fortnightly; Fungal: at first symptoms' },
    sowing: { method: 'Transplanting (nursery-raised seedlings)', depth: '1 cm nursery; transplant at collar level', spacing: '15x10 cm on raised beds', bestTime: 'Nursery: Oct; Transplanting: Dec-Jan (Rabi)', seedRate: '4-5 kg/acre (nursery seed)' },
    harvest: { timing: '100-120 DAT', signs: 'Tops fall over (neck fall), bulbs mature, outer scales dry', method: 'Manual pulling; cure in shade for 3-5 days', yield: '80-120 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'onion', soilType: 'black', season: 'kharif', region: 'karnataka',
    fertilizer: { type: 'NPK 10:26:26 + Urea', quantity: '50 kg NPK complex + 30 kg Urea per acre', schedule: 'Complex basal; Urea at 30 DAT', notes: 'Kharif onion is short-day type; avoid excess N which delays bulbing' },
    irrigation: { method: 'Drip irrigation', frequency: 'Every 2-3 days', waterPerAcre: '400 litres/day', notes: 'Kharif season has rain; ensure drainage in black soils. Raised bed planting mandatory.' },
    pest: { commonPests: ['Thrips', 'Anthracnose', 'Purple Blotch', 'Damping Off'], prevention: 'Nursery: Drench Metalaxyl; Main field: avoid waterlogging', treatment: 'Profenofos 50EC @10ml/10L for thrips; Tebuconazole for anthracnose', spraySchedule: 'From 20 DAT every 10 days' },
    sowing: { method: 'Transplanting on raised beds', depth: 'Collar at soil level', spacing: '15x10 cm', bestTime: 'Nursery: May-Jun; Transplanting: Jul-Aug', seedRate: '5 kg/acre' },
    harvest: { timing: '80-95 DAT', signs: 'Neck fall, bulb size 4-6 cm diameter', method: 'Pull and field cure 2-3 days', yield: '60-80 q/acre (kharif yields lower)' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'onion', soilType: 'alluvial', season: 'rabi', region: 'rajasthan',
    fertilizer: { type: 'DAP + MOP + Urea', quantity: 'DAP 50 kg, MOP 25 kg, Urea 35 kg per acre', schedule: 'P&K basal; N in 2 splits at transplanting and 30 DAT', notes: 'Rajasthan Alwar/Sikar belt onion for export market. Good sulphur application improves quality.' },
    irrigation: { method: 'Sprinkler / Flood', frequency: 'Every 5-7 days', waterPerAcre: '350 litres/day', notes: 'Light frequent irrigation preferred. Cut irrigation 15 days before harvest.' },
    pest: { commonPests: ['Thrips', 'Purple Blotch', 'White Rot'], prevention: 'Crop rotation (3-year cycle), disease-free seedlings', treatment: 'Lambda-cyhalothrin 5EC @5ml/10L for thrips; Tebuconazole 25.9EC @7ml/10L for diseases', spraySchedule: 'Fortnightly from 25 DAT' },
    sowing: { method: 'Transplanting', depth: 'Collar level', spacing: '15x10 cm', bestTime: 'Nursery: Nov; Transplanting: Jan', seedRate: '4-5 kg/acre' },
    harvest: { timing: '100-115 DAT', signs: 'Tops falling, neck softening', method: 'Manual harvesting + curing', yield: '80-100 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'onion', soilType: 'loamy', season: 'rabi', region: 'madhya pradesh',
    fertilizer: { type: 'DAP + Urea + MOP + Sulphur', quantity: 'DAP 50 kg, Urea 35 kg, MOP 25 kg, Sulphur 10 kg per acre', schedule: 'Basal complex + N top dressing at 30 and 50 DAT', notes: 'MP Indore/Mandsaur belt is large onion producing zone' },
    irrigation: { method: 'Drip / Sprinkler', frequency: 'Every 4-6 days', waterPerAcre: '350 litres/day', notes: 'Avoid excess water at bulb maturity; stop irrigation 10 days before harvest' },
    pest: { commonPests: ['Thrips', 'Downy Mildew', 'Stemphylium Blight'], prevention: 'Wider spacing for air circulation, avoid overhead irrigation', treatment: 'Fipronil 5SC @15ml/10L for thrips; Mancozeb+Metalaxyl for downy mildew', spraySchedule: 'From bulb initiation, every 10-12 days' },
    sowing: { method: 'Transplanting', depth: 'Collar at soil surface', spacing: '15x10 cm', bestTime: 'Nursery: Nov; Transplanting: Dec-Jan', seedRate: '4 kg/acre' },
    harvest: { timing: '105-120 DAT', signs: 'Neck fall >50%, outer scales papery', method: 'Manual pulling, field cure, then store in ventilated structure', yield: '90-120 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'onion', soilType: 'sandy', season: 'zaid', region: 'gujarat',
    fertilizer: { type: 'NPK 19:19:19 + Urea', quantity: '50 kg NPK complex + 30 kg Urea per acre', schedule: 'Basal NPK + Urea top dress at 25 and 45 DAT', notes: 'Summer onion in Gujarat for off-season premium price. Use mulching to reduce soil temperature.' },
    irrigation: { method: 'Drip irrigation', frequency: 'Daily in summer', waterPerAcre: '500 litres/day', notes: 'Sandy soils lose moisture fast; daily drip essential. Mulch with paddy straw.' },
    pest: { commonPests: ['Thrips', 'Leaf Blight', 'Fusarium Basal Rot'], prevention: 'Soil solarization before planting, Trichoderma viride soil application', treatment: 'Spinosad 45SC @3ml/10L for thrips; Copper Oxychloride for diseases', spraySchedule: 'Weekly in summer due to high pest pressure' },
    sowing: { method: 'Transplanting / Set planting', depth: 'Collar at soil level', spacing: '15x10 cm', bestTime: 'Feb-Mar (Summer/Zaid)', seedRate: '4 kg/acre (seed) or 4 q/acre (sets)' },
    harvest: { timing: '75-90 DAT', signs: 'Neck fall, bulbs firm', method: 'Manual pulling', yield: '60-80 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'onion', soilType: 'any', season: 'any', region: 'any',
    fertilizer: { type: 'DAP + MOP + Urea + Sulphur', quantity: 'DAP 50 kg, MOP 25 kg, Urea 35-40 kg, Sulphur 10 kg per acre', schedule: 'Full P, K, S as basal; N in 2-3 splits at transplanting, 30, and 50 DAT', notes: 'Sulphur improves pungency and storability. Apply FYM 5 t/acre. Avoid fresh FYM (causes double bulbing).' },
    irrigation: { method: 'Drip / Sprinkler irrigation', frequency: 'Every 3-7 days depending on soil and season', waterPerAcre: '350-500 litres/day', notes: 'Stop irrigation 10-15 days before harvest. Raised beds improve drainage and bulb shape.' },
    pest: { commonPests: ['Thrips', 'Purple Blotch', 'Stemphylium Blight', 'Basal/Fusarium Rot', 'Anthracnose'], prevention: 'Raised beds, proper spacing (15x10 cm), crop rotation, clean seedlings', treatment: 'Fipronil 5SC @15ml/10L for thrips; Mancozeb + Carbendazim combo for fungal diseases', spraySchedule: 'Fortnightly from 3 weeks after transplanting till 2 weeks before harvest' },
    sowing: { method: 'Transplanting (5-6 week old seedlings)', depth: '1 cm in nursery; transplant at collar level', spacing: '15x10 cm on raised beds', bestTime: 'Kharif: Jul-Aug; Rabi: Dec-Jan; Summer: Feb-Mar', seedRate: '4-5 kg/acre' },
    harvest: { timing: '80-120 DAT', signs: 'Tops fall over (neck fall), outer skin papery, bulbs firm', method: 'Manual pulling; cure/dry in shade for 3-5 days before grading and storage', yield: '60-120 q/acre depending on season and variety' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },

  // ============================================================
  // CHILLI (Kharif/Rabi, no MSP)
  // ============================================================
  {
    crop: 'chilli', soilType: 'black', season: 'kharif', region: 'andhra pradesh',
    fertilizer: { type: 'DAP + MOP + Urea + MgSO4', quantity: 'DAP 50 kg, MOP 30 kg, Urea 50 kg, MgSO4 10 kg per acre', schedule: 'P&K basal; N in 4 splits at transplanting, 30, 60, 90 DAT; MgSO4 foliar at flowering', notes: 'Guntur is chilli capital of India. Apply FYM 5 t/acre. Foliar micronutrients enhance colour.' },
    irrigation: { method: 'Drip irrigation', frequency: 'Every 3-5 days', waterPerAcre: '500 litres/day', notes: 'Avoid waterlogging (die-back and wilt). Mulch with paddy straw reduces soil splash.' },
    pest: { commonPests: ['Thrips', 'Mites', 'Fruit Borer', 'Leaf Curl Complex', 'Die-back', 'Anthracnose'], prevention: 'Yellow/blue sticky traps, border crops, IPM approach with biocontrol agents', treatment: 'Fipronil 5SC @15ml/10L for thrips; Propargite for mites; Copper Oxychloride + Mancozeb for die-back', spraySchedule: 'Weekly from flowering to fruit maturity due to multiple pest pressure' },
    sowing: { method: 'Transplanting (40-45 day old seedlings)', depth: '1 cm nursery; collar level transplant', spacing: '60x45 cm', bestTime: 'Nursery: Jun; Transplanting: Jul-Aug (Kharif)', seedRate: '200-250g/acre' },
    harvest: { timing: 'First harvest 75-80 DAT, continues for 4-5 months', signs: 'Fruits turn fully red, firm, glossy', method: 'Manual picking every 10-15 days for 5-8 pickings', yield: '30-50 q/acre (dry: 6-10 q/acre)' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'chilli', soilType: 'red', season: 'rabi', region: 'telangana',
    fertilizer: { type: 'NPK 19:19:19 + Urea + MOP', quantity: '40 kg NPK + 40 kg Urea + 20 kg MOP per acre', schedule: 'Basal NPK; Urea split at 25, 50, 75 DAT; MOP at 45 DAT', notes: 'Khammam/Warangal chilli belt. Apply neem cake 200 kg/acre for nematode control.' },
    irrigation: { method: 'Drip irrigation', frequency: 'Every 2-4 days', waterPerAcre: '450 litres/day', notes: 'Red soils dry fast; frequent light irrigation. Black plastic mulch improves moisture retention.' },
    pest: { commonPests: ['Thrips', 'Yellow Mite', 'Chilli Leaf Curl Virus', 'Powdery Mildew', 'Fruit Rot'], prevention: 'Resistant varieties (Teja, Byadgi), imidacloprid seed treatment', treatment: 'Diafenthiuron 50WP @12g/10L for mites/thrips; Wettable Sulphur 80WP @30g/10L for mildew', spraySchedule: 'From 20 DAT, spray every 10-12 days through harvest' },
    sowing: { method: 'Transplanting', depth: 'Collar level', spacing: '60x45 cm', bestTime: 'Nursery: Sep-Oct; Transplanting: Nov-Dec (Rabi)', seedRate: '200g/acre' },
    harvest: { timing: 'First harvest 70-75 DAT; multiple harvests over 4 months', signs: 'Red ripe fruits, glossy and firm', method: 'Hand picking in multiple rounds', yield: '25-40 q/acre (green); dry chilli 5-8 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'chilli', soilType: 'loamy', season: 'kharif', region: 'karnataka',
    fertilizer: { type: 'DAP + MOP + Urea', quantity: 'DAP 50 kg, MOP 25 kg, Urea 45 kg per acre', schedule: 'P&K basal; N in 3-4 splits over crop duration', notes: 'Byadgi chilli variety from Karnataka has GI tag. Apply Neem cake for soil health.' },
    irrigation: { method: 'Drip / Furrow', frequency: 'Every 4-6 days', waterPerAcre: '400 litres/day', notes: 'Loamy soils retain moisture well; avoid over-irrigation to prevent root rot' },
    pest: { commonPests: ['Thrips', 'White Fly', 'Anthracnose', 'Bacterial Wilt'], prevention: 'Raised bed planting, proper drainage, crop rotation with cereals', treatment: 'Spinosad 45SC @3ml/10L for thrips; Bordeaux mixture 1% for bacterial diseases', spraySchedule: 'Fortnightly spraying from flowering stage' },
    sowing: { method: 'Transplanting', depth: 'Collar at soil level', spacing: '60x45 cm (Byadgi: 45x30 cm)', bestTime: 'Nursery: May-Jun; Transplanting: Jul-Aug', seedRate: '200-300g/acre' },
    harvest: { timing: 'First pick at 75-80 DAT; continues 3-4 months', signs: 'Deep red color with characteristic wrinkles (Byadgi type)', method: 'Hand picking followed by sun drying for 8-10 days', yield: 'Dry: 5-8 q/acre (Byadgi); Green: 25-35 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'chilli', soilType: 'alluvial', season: 'rabi', region: 'west bengal',
    fertilizer: { type: 'Urea + SSP + MOP', quantity: 'Urea 45 kg, SSP 75 kg, MOP 25 kg per acre', schedule: 'P&K basal; N in 3 splits', notes: 'WB grows both chilli and capsicum. Apply lime in acidic alluvial soils of Bengal.' },
    irrigation: { method: 'Furrow / Channel irrigation', frequency: 'Every 5-7 days', waterPerAcre: '350 litres/day', notes: 'Winter crop needs less water. Protect from frost with smoke screens or mulch.' },
    pest: { commonPests: ['Aphids', 'Fruit Borer', 'Cercospora Leaf Spot', 'Mosaic Virus'], prevention: 'Reflective mulch for aphids (virus vector), balanced nutrition', treatment: 'Dimethoate 30EC @10ml/10L for aphids; Carbendazim 50WP @10g/10L for leaf spot', spraySchedule: 'At 25 DAT and at fruiting' },
    sowing: { method: 'Transplanting', depth: 'Collar at surface', spacing: '45x30 cm', bestTime: 'Nursery: Oct; Transplanting: Nov-Dec', seedRate: '250g/acre' },
    harvest: { timing: '65-75 DAT first pick; 3-4 months harvest window', signs: 'Green chilli: dark green, firm; Red: fully coloured', method: 'Hand picking for green chilli every 7-10 days', yield: 'Green: 40-60 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'chilli', soilType: 'sandy', season: 'rabi', region: 'rajasthan',
    fertilizer: { type: 'DAP + MOP + Urea', quantity: 'DAP 45 kg, MOP 20 kg, Urea 40 kg per acre', schedule: 'Basal P&K; N through fertigation weekly', notes: 'Jodhpur/Mathania chilli (Mathania variety) famous for colour and pungency. Sandy soils need fertigation.' },
    irrigation: { method: 'Drip irrigation', frequency: 'Daily in dry season', waterPerAcre: '500 litres/day', notes: 'Sandy soils: daily drip is essential. Mulching reduces evaporation significantly.' },
    pest: { commonPests: ['Thrips', 'Mites', 'Die-back', 'Fruit Rot'], prevention: 'Mulching reduces splash-borne diseases, use neem-based sprays as preventive', treatment: 'Abamectin 1.8EC @5ml/10L for mites; Copper Hydroxide 77WP @20g/10L for die-back', spraySchedule: 'Weekly from transplanting in dry conditions' },
    sowing: { method: 'Transplanting on mulched beds', depth: 'Collar level', spacing: '60x45 cm', bestTime: 'Nursery: Sep-Oct; Transplanting: Nov', seedRate: '200g/acre' },
    harvest: { timing: '70-80 DAT first pick', signs: 'Full red colour, sun-dried for Mathania quality', method: 'Hand picking + sun drying on clean surface', yield: 'Dry: 4-7 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
  {
    crop: 'chilli', soilType: 'any', season: 'any', region: 'any',
    fertilizer: { type: 'DAP + MOP + Urea', quantity: 'DAP 50 kg, MOP 25 kg, Urea 40-50 kg per acre', schedule: 'Full P&K basal; N in 3-4 splits at transplanting, 30, 60, 90 DAT', notes: 'Apply FYM 5 t/acre. Micronutrients (Mg, B, Zn) improve fruit quality and colour. Avoid excess N (reduces pungency).' },
    irrigation: { method: 'Drip irrigation (recommended)', frequency: 'Every 3-5 days depending on soil and climate', waterPerAcre: '400-500 litres/day', notes: 'Mulching reduces disease and water use. Avoid wetting foliage. Stop heavy irrigation before picking.' },
    pest: { commonPests: ['Thrips', 'Mites', 'Fruit Borer', 'Leaf Curl Virus', 'Die-back', 'Anthracnose', 'Powdery Mildew'], prevention: 'Sticky traps, resistant/tolerant varieties, IPM approach, proper spacing', treatment: 'Fipronil/Spinosad for thrips; Propargite/Abamectin for mites; Copper-based fungicides for bacterial/fungal diseases', spraySchedule: 'Regular schedule from 20 DAT: every 10-12 days during flowering and fruiting period' },
    sowing: { method: 'Transplanting (40-50 day old nursery seedlings)', depth: '1 cm in nursery; transplant at collar level on raised beds', spacing: '60x45 cm to 45x30 cm', bestTime: 'Kharif: Jul-Aug; Rabi: Nov-Dec', seedRate: '200-300g/acre' },
    harvest: { timing: 'First harvest 65-80 DAT; continues for 3-5 months with 5-8 pickings', signs: 'Green: dark green, firm; Red: fully coloured, glossy', method: 'Manual picking at desired maturity; sun dry for 8-10 days for dry chilli', yield: 'Green: 25-60 q/acre; Dry: 5-10 q/acre' },
    msp: { price: 0, unit: '₹/quintal', year: '2024-25' },
  },
];

module.exports = cropRules;
