/**
 * KrishiSathi - Agriculture News Seed Data
 * 20 realistic Indian agriculture news articles across multiple categories
 */

const news = [
  {
    title: 'Rabi season wheat procurement to begin from April 1 across major producing states',
    content: 'The Government of India has announced that the procurement of wheat for the Rabi 2025-26 season will commence from April 1, 2026 across Punjab, Haryana, Madhya Pradesh, Uttar Pradesh, and Rajasthan. The Food Corporation of India (FCI) and state agencies have set up over 20,000 procurement centres to ensure smooth operations.\n\nThe minimum support price for wheat has been fixed at Rs. 2,275 per quintal for the marketing season 2025-26. The government targets procuring 320 lakh metric tonnes to maintain adequate buffer stocks and support the public distribution system. Officials from the Department of Food and Public Distribution have directed state governments to complete all preparatory measures including arrangement of gunny bags, transportation, and storage space.\n\nFarmers are advised to bring their produce to designated mandis and procurement centres with proper documentation including Aadhaar card, land records, and bank account details for direct payment through DBT. The procurement will continue until June 15 in most states.',
    summary: 'Government announces April 1 start for wheat procurement at MSP of Rs. 2,275/quintal across major producing states with 20,000+ centres.',
    category: 'policy',
    source: 'Ministry of Agriculture',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['wheat', 'MSP', 'procurement', 'rabi', 'FCI'],
    region: 'pan-india',
    publishedAt: new Date('2026-02-20T10:00:00Z'),
  },
  {
    title: 'IMD forecasts above-normal temperatures in February-March, advisories issued for standing crops',
    content: 'The India Meteorological Department (IMD) has forecast above-normal maximum temperatures across northwest and central India during the remaining February and March period. Day temperatures are expected to be 2-3 degrees Celsius above the long-period average in Punjab, Haryana, western UP, Rajasthan, and parts of Madhya Pradesh.\n\nThe heat wave conditions may adversely impact the wheat crop which is currently in the critical grain filling stage. Agricultural scientists from ICAR have issued advisories recommending farmers to provide light irrigation at weekly intervals to mitigate heat stress effects. The phenomenon of terminal heat stress can cause significant yield reduction if grain filling coincides with temperatures above 35 degrees Celsius.\n\nFor standing mustard, chickpea, and rabi vegetable crops, farmers have been advised to apply straw mulching, ensure adequate irrigation, and consider foliar spray of 0.5% potassium chloride solution to improve heat tolerance. Harvesting of matured crops should be expedited to avoid quality deterioration.',
    summary: 'IMD warns of above-normal temperatures in Feb-March. ICAR issues crop advisories to protect wheat during grain filling from terminal heat stress.',
    category: 'weather',
    source: 'IMD / ICAR',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['weather', 'heat-wave', 'wheat', 'rabi', 'IMD', 'advisory'],
    region: 'north-india',
    publishedAt: new Date('2026-02-19T08:30:00Z'),
  },
  {
    title: 'Cotton prices firm up as CCI increases procurement pace in Telangana and Maharashtra',
    content: 'Cotton prices in major mandis of Telangana and Maharashtra have firmed up following increased procurement by the Cotton Corporation of India (CCI) at the minimum support price of Rs. 7,121 per quintal for medium staple and Rs. 7,521 for long staple varieties. CCI has set up 430 procurement centres across the two states for the 2025-26 season.\n\nIn Warangal and Adilabad mandis, cotton (kapas) is trading between Rs. 6,800-7,200 per quintal with premium varieties fetching above MSP. The arrival of cotton in mandis has been steady with approximately 45 lakh bales procured so far this season. Industry sources indicate that total cotton production for 2025-26 is estimated at 302 lakh bales, marginally lower than last year due to pest issues in parts of Gujarat and Rajasthan.\n\nTraders and ginners are actively competing with CCI in procurement, which has supported market prices. The Confederation of Indian Textile Industry (CITI) has urged the government to ensure adequate availability for the domestic textile industry while maintaining price stability for farmers.',
    summary: 'Cotton prices strengthen as CCI ramps up MSP procurement in Telangana and Maharashtra. Market prices near Rs. 7,000-7,200/quintal in major mandis.',
    category: 'market',
    source: 'CCI / Market Reports',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['cotton', 'CCI', 'MSP', 'procurement', 'telangana', 'maharashtra'],
    region: 'south-india',
    publishedAt: new Date('2026-02-18T11:00:00Z'),
  },
  {
    title: 'PM-KISAN 20th instalment of Rs. 2,000 released to over 9 crore farmers',
    content: 'Prime Minister Narendra Modi released the 20th instalment of the Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) scheme, transferring Rs. 2,000 each to over 9.2 crore farmer families across the country. The total disbursement of Rs. 18,400 crore was done through Direct Benefit Transfer (DBT) in a single click during a video conference event.\n\nSince its inception in February 2019, the PM-KISAN scheme has transferred over Rs. 3.24 lakh crore to farmer families. The scheme provides an annual income support of Rs. 6,000 in three equal instalments to all landholding farmer families irrespective of the size of their landholdings. Beneficiaries can check their payment status on the PM-KISAN portal (pmkisan.gov.in) or through the mobile app.\n\nThe government has also intensified the eKYC verification process to eliminate ineligible beneficiaries. Farmers who have not completed Aadhaar-based eKYC are urged to do so immediately to avoid disruption in future instalments. State agriculture departments have been directed to organize camps in rural areas to facilitate eKYC completion for elderly and differently-abled farmers.',
    summary: 'PM-KISAN 20th instalment of Rs. 2,000 released to 9.2 crore farmers. Total disbursement since inception crosses Rs. 3.24 lakh crore.',
    category: 'schemes',
    source: 'PIB / Ministry of Agriculture',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['PM-KISAN', 'subsidy', 'DBT', 'farmer-welfare'],
    region: 'pan-india',
    publishedAt: new Date('2026-02-17T09:00:00Z'),
  },
  {
    title: 'Onion prices surge 40% in Delhi-NCR as summer supply tightens',
    content: 'Retail onion prices in Delhi-NCR have surged by nearly 40% over the past two weeks, rising from Rs. 25 per kg to Rs. 35 per kg as the stored rabi onion stocks from last year are depleting and the new late kharif crop arrivals have reduced. In Azadpur mandi, the wholesale price of onion has moved from Rs. 1,200 to Rs. 1,800 per quintal during this period.\n\nMarket analysts attribute the price rise to the seasonal gap between the depletion of stored onion from the previous rabi season and the arrival of the fresh rabi crop which is expected from April onwards. The government has directed NAFED and NCCF to release buffer stock onions at subsidized rates through mobile vans and retail outlets to moderate prices in major consuming centres.\n\nConsumer Affairs Secretary has stated that approximately 3 lakh tonnes of onion buffer stock is available and will be released in a phased manner. Additionally, the government is monitoring arrivals in key producing states of Maharashtra, Madhya Pradesh, and Karnataka. Farmers in Nashik district report that the standing rabi onion crop is in good condition and harvesting is expected to begin by end of March.',
    summary: 'Onion prices jump 40% in Delhi-NCR due to seasonal supply gap. Government releasing buffer stocks through NAFED to moderate retail prices.',
    category: 'market',
    source: 'Consumer Affairs Ministry',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['onion', 'price-rise', 'Delhi', 'NAFED', 'buffer-stock'],
    region: 'north-india',
    publishedAt: new Date('2026-02-16T14:00:00Z'),
  },
  {
    title: 'ICAR launches AI-powered pest surveillance system for real-time crop monitoring',
    content: 'The Indian Council of Agricultural Research (ICAR) has launched an artificial intelligence-powered National Pest Surveillance System (NPSS) that uses satellite imagery, drone-based sensors, and farmer-reported data to provide real-time pest and disease alerts to farmers. The system covers 15 major crops and can predict pest outbreaks up to 2 weeks in advance with 85% accuracy.\n\nDeveloped in collaboration with IIT Hyderabad and ISRO, the system uses machine learning models trained on 10 years of historical pest surveillance data from 650 districts. Farmers can receive location-specific alerts through SMS, WhatsApp, and the KisanMitr mobile application in 12 Indian languages. The system also provides AI-generated treatment recommendations based on the identified pest species and crop growth stage.\n\nThe pilot programme run in 50 districts of Andhra Pradesh, Telangana, Maharashtra, and Madhya Pradesh during Kharif 2025 showed a 25% reduction in pesticide usage and 15% reduction in crop losses in participating farms. The system is now being expanded nationwide with the support of state agriculture departments and Krishi Vigyan Kendras.',
    summary: 'ICAR launches AI pest surveillance system using satellite and drone data for real-time alerts. Pilot showed 25% reduction in pesticide use across 50 districts.',
    category: 'technology',
    source: 'ICAR',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['technology', 'AI', 'pest-management', 'ICAR', 'drones', 'satellite'],
    region: 'pan-india',
    publishedAt: new Date('2026-02-15T10:30:00Z'),
  },
  {
    title: 'Fall Armyworm alert issued for rabi maize in Bihar and Jharkhand',
    content: 'The Central Integrated Pest Management Centre (CIPMC) has issued an alert regarding the increasing incidence of Fall Armyworm (Spodoptera frugiperda) in rabi maize crops across Bihar and Jharkhand. Field surveys indicate infestation levels of 15-25% in several districts of Bihar including Begusarai, Samastipur, Khagaria, and Bhagalpur where rabi maize is at the critical tasseling to grain filling stage.\n\nThe invasive pest, first detected in India in 2018, has become a major threat to maize production. Agricultural scientists recommend immediate action including application of Emamectin Benzoate 5% SG at 4g per 10 litres of water or Chlorantraniliprole 18.5% SC at 3ml per 10 litres water targeting the whorl region. For early-stage infestation, application of sand mixed with lime in the whorl (1:1 ratio) is recommended as a low-cost alternative.\n\nKrishi Vigyan Kendras in affected districts are organizing field demonstrations and distributing pheromone traps at subsidized rates. Farmers are advised to monitor their fields regularly and report any unusual leaf feeding damage or frass (insect excrement) in the whorl to their nearest KVK or agriculture department office.',
    summary: 'Fall Armyworm alert in Bihar-Jharkhand rabi maize. CIPMC recommends Emamectin Benzoate or Chlorantraniliprole sprays at tasseling stage.',
    category: 'advisory',
    source: 'CIPMC / State Agriculture Dept',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['maize', 'fall-armyworm', 'pest-alert', 'bihar', 'jharkhand', 'rabi'],
    region: 'east-india',
    publishedAt: new Date('2026-02-14T09:00:00Z'),
  },
  {
    title: 'e-NAM crosses milestone of 1,500 mandis with integration of 139 new markets',
    content: 'The National Agriculture Market (e-NAM) platform has achieved the milestone of integrating 1,500 mandis across 23 states and 3 Union Territories, with the addition of 139 new mandis in the current financial year. The electronic trading platform, launched in 2016, now facilitates trading in 209 commodities including food grains, oilseeds, spices, fruits, and vegetables.\n\nThe cumulative trade value on e-NAM has crossed Rs. 3.5 lakh crore with over 1.76 crore farmer registrations and 2.5 lakh trader registrations. The platform has been particularly successful in reducing price asymmetry between mandis, with studies showing that inter-mandi price variation has reduced by 8-12% for major commodities since its implementation. Quality assaying facilities using AGMARK parameters have been established in 450 mandis.\n\nThe government plans to integrate all remaining APMC mandis by March 2027 and is working on logistics integration to enable seamless inter-state trade. New features including warehouse-based trading without physical movement to mandi, integration with FPO (Farmer Producer Organization) modules, and commodity-based financing are being rolled out in phases.',
    summary: 'e-NAM reaches 1,500 mandis milestone across 23 states. Cumulative trade value crosses Rs. 3.5 lakh crore with 1.76 crore farmers registered.',
    category: 'policy',
    source: 'Ministry of Agriculture',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['e-NAM', 'mandis', 'marketing', 'digital-agriculture'],
    region: 'pan-india',
    publishedAt: new Date('2026-02-13T12:00:00Z'),
  },
  {
    title: 'Telangana announces Rs. 500 crore package for drought-affected districts',
    content: 'The Telangana state government has announced a special relief package of Rs. 500 crore for farmers in drought-affected districts of Nalgonda, Mahabubnagar, Jogulamba-Gadwal, and Wanaparthy where the kharif 2025 season witnessed 30-40% deficit rainfall. The package includes input subsidy of Rs. 10,000 per acre for crop loss exceeding 33%, additional subsidized seeds for compensatory rabi sowing, and waiver of crop loan interest for the affected season.\n\nAn assessment by the state agriculture department found that approximately 4.5 lakh acres across these districts suffered significant crop damage, primarily affecting cotton, maize, and red gram cultivation. The Chief Minister directed officials to complete the enumeration and disbursal process within 45 days to ensure timely relief to affected farming families.\n\nIn addition to the relief package, the state government is also providing subsidized drip irrigation systems and farm pond construction to help farmers adopt water-efficient practices. The Rythu Bandhu scheme income support of Rs. 5,000 per acre per season will continue as per schedule for all registered farmers.',
    summary: 'Telangana announces Rs. 500 crore drought relief for 4 districts. Rs. 10,000/acre input subsidy for farmers with >33% crop loss.',
    category: 'policy',
    source: 'Telangana State Government',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['telangana', 'drought-relief', 'subsidy', 'cotton', 'maize'],
    region: 'telangana',
    publishedAt: new Date('2026-02-12T15:00:00Z'),
  },
  {
    title: 'Tomato prices crash to Rs. 5/kg in Karnataka as bumper rabi harvest floods mandis',
    content: 'Tomato growers in Karnataka are facing severe distress as wholesale prices have plummeted to Rs. 400-500 per quintal (Rs. 4-5 per kg) in Kolar, Chikkaballapur, and Ramanagara districts due to a bumper rabi harvest coinciding with peak arrivals. Daily arrivals at Kolar mandi alone have exceeded 3,000 tonnes, compared to the normal 1,500-2,000 tonnes, leading to a glut situation.\n\nFarmers report that the cost of production for tomato is approximately Rs. 8-10 per kg, meaning current prices result in losses of Rs. 4-6 per kg. Many farmers are leaving their produce unpicked in the fields as harvesting and transportation costs exceed the market realization. The Karnataka state farmers\' association has demanded government intervention including direct procurement, promotion of tomato processing, and export facilitation.\n\nAgricultural economists suggest that the price crash highlights the need for better market intelligence, cold chain infrastructure, and crop diversification. The government-run tomato paste and puree manufacturing units in Kolar and Bellary have been asked to increase their procurement to absorb some of the surplus production. Industry experts recommend that farmers explore forward contracts and direct tie-ups with processors to reduce price volatility.',
    summary: 'Tomato prices crash to Rs. 5/kg in Karnataka due to bumper harvest glut. Farmers demand government intervention and processing facility support.',
    category: 'market',
    source: 'Karnataka Agriculture Dept',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['tomato', 'price-crash', 'karnataka', 'market-glut', 'farmer-distress'],
    region: 'south-india',
    publishedAt: new Date('2026-02-11T13:00:00Z'),
  },
  {
    title: 'PMFBY claims settlement improves to 87% with drone-based crop cutting experiments',
    content: 'The Pradhan Mantri Fasal Bima Yojana (PMFBY) has achieved a claim settlement rate of 87% for the Kharif 2025 season, a significant improvement from 72% in the previous year, attributed largely to the adoption of drone-based crop cutting experiments (CCEs) and satellite-based yield estimation technology. The faster and more accurate yield assessment has reduced disputes and expedited claim processing.\n\nOver 5.6 crore farmer applications were received for Kharif 2025 coverage, with a total sum insured of Rs. 2.8 lakh crore. Claims worth Rs. 18,500 crore have been settled so far with the remaining expected to be processed by March-end. The use of technology has reduced the average claim settlement time from 6 months to under 2 months in most states. Weather-based crop insurance settlements for localized calamities have been further streamlined using automatic weather station (AWS) data.\n\nThe Agriculture Insurance Company (AIC) and private insurers participating in PMFBY have deployed over 2,000 drones across 450 districts for CCEs this season. The government is also piloting parametric insurance products for horticultural crops like tomato, onion, and mango to provide quicker payouts based on weather triggers rather than yield-based assessment.',
    summary: 'PMFBY claim settlement improves to 87% using drone-based crop assessment. Average settlement time reduced to under 2 months.',
    category: 'schemes',
    source: 'Ministry of Agriculture / AIC',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['PMFBY', 'crop-insurance', 'drones', 'technology', 'claims'],
    region: 'pan-india',
    publishedAt: new Date('2026-02-10T10:00:00Z'),
  },
  {
    title: 'Solar-powered irrigation pumps save 40% electricity cost for farmers in Rajasthan pilot',
    content: 'A pilot programme under the PM-KUSUM (Pradhan Mantri Kisan Urja Suraksha evam Utthan Mahabhiyan) scheme in Jodhpur and Barmer districts of Rajasthan has demonstrated that solar-powered irrigation pumps can reduce electricity costs by 40% while also enabling surplus power sale to the grid. The programme covered 5,000 farmers who replaced diesel and electric pumps with solar pump systems of 3-7.5 HP capacity.\n\nThe decentralized solar power generation model allows farmers to earn Rs. 5,000-8,000 per month by selling surplus solar electricity to the state grid at Rs. 3.50 per unit through net metering. The capital subsidy of 60% (30% central + 30% state) has made the systems affordable with farmers paying only 40% of the total cost, often financed through Kisan Credit Card loans.\n\nThe Rajasthan Renewable Energy Corporation (RREC) plans to expand the programme to 50,000 additional farmers across the state in 2026-27. The success of the pilot has prompted similar programmes in Gujarat, Maharashtra, and Andhra Pradesh. Water use efficiency has also improved as solar pumps encourage daytime irrigation, reducing the practice of wasteful overnight flood irrigation common with subsidized grid electricity.',
    summary: 'PM-KUSUM solar pumps save 40% electricity cost in Rajasthan pilot with 5,000 farmers. Surplus power sale earns Rs. 5,000-8,000/month.',
    category: 'technology',
    source: 'MNRE / RREC',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['solar', 'irrigation', 'PM-KUSUM', 'rajasthan', 'renewable-energy'],
    region: 'west-india',
    publishedAt: new Date('2026-02-09T11:00:00Z'),
  },
  {
    title: 'Groundnut oil prices rise sharply as international edible oil markets tighten',
    content: 'Groundnut oil prices in the domestic market have risen by 15% over the past month, with refined groundnut oil now trading at Rs. 180-200 per litre in major consuming centres of Gujarat and Rajasthan. The price rise is attributed to tight international edible oil supplies, lower domestic groundnut production, and strong export demand for Indian HPS groundnut kernels.\n\nIndia\'s groundnut production for 2025-26 kharif season is estimated at 78 lakh tonnes, about 8% lower than last year due to erratic rainfall in Gujarat and Andhra Pradesh. The lower production has pushed raw groundnut prices in Rajkot and Junagadh mandis to Rs. 6,500-7,000 per quintal, approaching the MSP level. Meanwhile, international palm oil and soybean oil prices have also firmed up due to lower production in Indonesia and Brazil.\n\nThe Solvent Extractors\' Association of India (SEA) has noted that the rising edible oil prices may prompt the government to reduce import duties to control retail inflation. However, farmer organizations have opposed any duty reduction arguing that it would depress domestic oilseed prices and discourage production. The government is reportedly considering targeted distribution through PDS rather than across-the-board duty cuts.',
    summary: 'Groundnut oil prices surge 15% on tight supply and strong export demand. Domestic production down 8% due to erratic rainfall.',
    category: 'market',
    source: 'SEA / Market Reports',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['groundnut', 'edible-oil', 'price-rise', 'gujarat', 'oilseeds'],
    region: 'west-india',
    publishedAt: new Date('2026-02-08T14:00:00Z'),
  },
  {
    title: 'Yellow rust alert for wheat in Punjab and Haryana: agriculture department issues spray advisory',
    content: 'The Punjab and Haryana agriculture departments have issued an alert regarding the appearance of yellow rust (stripe rust) in wheat crops in some pockets of Bathinda, Mansa, Fazilka, and Sirsa districts. The disease, caused by Puccinia striiformis, thrives in cool and humid conditions prevalent during February and can spread rapidly if not controlled in time.\n\nFarmers have been advised to spray Propiconazole 25% EC at 10ml per 10 litres of water or Tebuconazole 25.9% EC at 7.5ml per 10 litres of water immediately upon noticing yellow-orange pustules on leaves. The spray should be repeated after 15 days if the disease persists. PAU (Punjab Agricultural University) scientists have confirmed that the currently grown varieties including PBW-824 and HD-3226 have moderate resistance but can succumb under high disease pressure.\n\nThe state governments have directed district agriculture officers to conduct intensive field surveys and organize awareness camps in affected areas. Free fungicide kits are being distributed through primary agricultural cooperative societies. Farmers are also advised to avoid excessive nitrogen application which makes the crop more susceptible to rust infection.',
    summary: 'Yellow rust detected in Punjab-Haryana wheat. Farmers advised to spray Propiconazole immediately. Free fungicide distribution through cooperatives.',
    category: 'advisory',
    source: 'Punjab/Haryana Agriculture Dept',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['wheat', 'yellow-rust', 'punjab', 'haryana', 'fungicide', 'advisory'],
    region: 'north-india',
    publishedAt: new Date('2026-02-18T08:00:00Z'),
  },
  {
    title: 'Sugarcane FRP increased to Rs. 340/quintal for 2026-27 season by CACP recommendation',
    content: 'The Commission for Agricultural Costs and Prices (CACP) has recommended an increase in the Fair and Remunerative Price (FRP) of sugarcane to Rs. 340 per quintal for the 2026-27 sugar season, up from Rs. 315 per quintal. The recommendation is linked to a basic recovery rate of 10.25%, with a premium of Rs. 3.40 per quintal for every 0.1% increase in recovery above this level.\n\nThe sugar industry has expressed concerns about the proposed increase, stating that mills are already under financial stress with pending cane arrears of Rs. 8,000 crore to farmers from the current season. The Indian Sugar Mills Association (ISMA) has requested the government to simultaneously increase the minimum selling price of sugar from the current Rs. 31 per kg to Rs. 38 per kg to make the higher FRP viable for mills.\n\nFarmer organizations including BKU have welcomed the recommendation but argued that the increase is inadequate given the rise in input costs. They have demanded an FRP of Rs. 400 per quintal. The final decision rests with the Cabinet Committee on Economic Affairs (CCEA) which is expected to take a call before the onset of the crushing season in October.',
    summary: 'CACP recommends sugarcane FRP increase to Rs. 340/quintal from Rs. 315. Sugar mills demand concurrent hike in minimum selling price of sugar.',
    category: 'policy',
    source: 'CACP / Ministry of Agriculture',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['sugarcane', 'FRP', 'CACP', 'sugar-mills', 'pricing-policy'],
    region: 'pan-india',
    publishedAt: new Date('2026-02-07T09:30:00Z'),
  },
  {
    title: 'Guntur chilli prices touch Rs. 17,000/quintal as export demand from China and Southeast Asia surges',
    content: 'Dried red chilli prices at the Guntur agriculture market yard in Andhra Pradesh have touched Rs. 17,000 per quintal for the premium Teja variety, the highest level in two years. The price surge is driven by strong export demand from China, Bangladesh, Sri Lanka, and Southeast Asian countries, combined with lower carry-over stocks from the previous season.\n\nIndia is the world\'s largest producer, consumer, and exporter of chilli, with an annual production of about 20 lakh tonnes. Guntur district alone accounts for nearly 30% of India\'s chilli production. The current season\'s harvest is progressing well with arrivals of 30,000-40,000 bags per day at the Guntur market yard. However, quality premium has widened significantly - while Teja variety commands Rs. 15,000-17,000/quintal, lower grades are trading at Rs. 8,000-10,000/quintal.\n\nExporters report that Chinese buyers have increased orders by 25% year-on-year due to lower production in Sichuan province. The Spices Board India has set an export target of 5.5 lakh tonnes of chilli for FY2026 valued at Rs. 12,000 crore. Farmers in Khammam and Warangal districts of Telangana are also benefiting from the price surge as their produce flows to the Guntur market.',
    summary: 'Guntur chilli prices hit Rs. 17,000/quintal (Teja variety) on strong Chinese export demand. India targets 5.5 lakh tonnes chilli exports.',
    category: 'market',
    source: 'Spices Board India / Guntur Market',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['chilli', 'guntur', 'export', 'price-rise', 'spices'],
    region: 'south-india',
    publishedAt: new Date('2026-02-14T16:00:00Z'),
  },
  {
    title: 'NABARD sanctions Rs. 2,500 crore for rural cold chain and warehouse infrastructure',
    content: 'The National Bank for Agriculture and Rural Development (NABARD) has sanctioned Rs. 2,500 crore under the Agriculture Infrastructure Fund (AIF) for the construction of cold chain facilities, warehouses, and pack houses across 15 states. The projects will create storage capacity for 25 lakh tonnes of perishable and semi-perishable agricultural produce.\n\nThe fund provides interest subvention of 3% per annum on loans up to Rs. 2 crore for individual entrepreneurs, FPOs, and agri-startups investing in post-harvest management infrastructure. Additionally, credit guarantee coverage is available through CGTMSE. Priority is being given to districts identified as major production clusters for fruits, vegetables, and dairy products.\n\nKey projects sanctioned include multi-commodity cold stores in Nashik (Maharashtra), Kolar (Karnataka), and Sonipat (Haryana); integrated pack houses with grading and sorting facilities in apple-growing districts of Himachal Pradesh and J&K; and ripening chambers for banana in Jalgaon (Maharashtra) and Anantapur (Andhra Pradesh). NABARD has encouraged FPOs and cooperatives to take advantage of the scheme to reduce post-harvest losses which currently stand at 16% for fruits and vegetables.',
    summary: 'NABARD sanctions Rs. 2,500 crore for cold chain and warehouse projects across 15 states. 3% interest subvention available under AIF scheme.',
    category: 'schemes',
    source: 'NABARD',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['cold-chain', 'warehouse', 'NABARD', 'AIF', 'infrastructure'],
    region: 'pan-india',
    publishedAt: new Date('2026-02-06T10:00:00Z'),
  },
  {
    title: 'Soybean MSP procurement under PM-AASHA crosses 50 lakh tonnes in Madhya Pradesh',
    content: 'Soybean procurement under the Price Support Scheme (PSS) component of PM-AASHA has crossed 50 lakh tonnes in Madhya Pradesh, the largest producer of soybean in India. NAFED and state cooperative agencies have procured the commodity at the MSP of Rs. 4,892 per quintal through 1,200 procurement centres set up across 52 districts of the state.\n\nThe massive procurement operation, the largest ever for soybean in MP, was necessitated by market prices falling below MSP during the peak arrival period in October-November 2025. The total value of procurement exceeds Rs. 24,000 crore, providing direct income support to over 18 lakh soybean farmers. The procured soybean is being processed through solvent extraction plants for oil production, with the de-oiled cake being exported as animal feed.\n\nThe success of the operation has been attributed to the advance registration of farmers on the state portal, real-time monitoring through the PM-AASHA app, and direct DBT-based payment within 48 hours of procurement. However, storage and handling challenges remain, with NAFED currently utilizing 80% of its warehousing capacity in MP for soybean stocks.',
    summary: 'MP soybean procurement under PM-AASHA crosses 50 lakh tonnes at MSP of Rs. 4,892/quintal. Over 18 lakh farmers benefited through 1,200 centres.',
    category: 'policy',
    source: 'NAFED / MP Agriculture',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['soybean', 'MSP', 'PM-AASHA', 'NAFED', 'madhya-pradesh', 'procurement'],
    region: 'central-india',
    publishedAt: new Date('2026-02-05T11:00:00Z'),
  },
  {
    title: 'Nano urea and nano DAP adoption doubles among progressive farmers in 2025-26',
    content: 'The adoption of IFFCO\'s Nano Urea and the recently launched Nano DAP has doubled among progressive farmers in the 2025-26 season compared to the previous year, according to data from the Fertilizer Association of India. Over 15 crore bottles of Nano Urea and 4 crore bottles of Nano DAP have been sold across the country, covering an estimated 8 crore acres of cultivated area.\n\nNano Urea, priced at Rs. 225 per 500ml bottle (equivalent to one bag of conventional urea), has shown yield improvements of 5-8% in rice, wheat, and maize when used as a foliar supplement. The technology reduces conventional urea requirement by 25-50% while improving nitrogen use efficiency. Nano DAP, launched in 2024 at Rs. 600 per 500ml bottle, provides concentrated phosphorus nutrition and has been particularly effective in pulses and oilseeds.\n\nHowever, agricultural scientists have cautioned that nano fertilizers are supplements to, not substitutes for, soil-applied granular fertilizers. Basal soil application of NPK remains essential for proper root development and early crop growth. ICAR has recommended using nano formulations for 2nd and 3rd top-dressing applications to maximize their effectiveness. Several state governments are distributing nano fertilizers at subsidized rates through cooperative societies.',
    summary: 'Nano Urea and Nano DAP adoption doubles in 2025-26. 15 crore bottles sold, covering 8 crore acres. 5-8% yield improvement reported.',
    category: 'technology',
    source: 'IFFCO / FAI',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['nano-urea', 'nano-DAP', 'IFFCO', 'fertilizer', 'technology'],
    region: 'pan-india',
    publishedAt: new Date('2026-02-13T08:30:00Z'),
  },
  {
    title: 'Rice exporters seek relaxation of MEP as global prices stabilize',
    content: 'Indian rice exporters and the All India Rice Exporters Association (AIREA) have urged the government to relax the minimum export price (MEP) restrictions on basmati rice and lift the ban on non-basmati white rice exports as global prices have stabilized and domestic stocks are comfortable. The current restrictions, imposed in 2023 to control domestic inflation, have cost Indian exporters an estimated $3 billion in lost revenue.\n\nIndia\'s rice production for 2025-26 is estimated at a record 140 million tonnes, with government procurement reaching 55 million tonnes. The buffer stock of rice as on January 1, 2026 stands at 42 million tonnes against the requirement of 13.5 million tonnes, providing more than adequate food security cover. Global rice prices have also moderated by 20% from their 2023 peaks following good harvests in Thailand and Vietnam.\n\nThe Food Ministry is reportedly considering a phased relaxation - first reducing the MEP for basmati from $950/tonne to $800/tonne and then allowing non-basmati white rice exports with a 20% duty. Trade analysts expect a decision before the upcoming WTO ministerial meeting. The relaxation would benefit over 2 crore rice farmers, particularly in Punjab, Haryana, Telangana, and Andhra Pradesh, by strengthening domestic prices.',
    summary: 'Rice exporters seek MEP relaxation and non-basmati export ban lift. Record production and comfortable stocks support the case for trade liberalization.',
    category: 'policy',
    source: 'AIREA / Commerce Ministry',
    imageUrl: '',
    language: 'en',
    isAiGenerated: false,
    tags: ['rice', 'export', 'MEP', 'trade-policy', 'basmati'],
    region: 'pan-india',
    publishedAt: new Date('2026-02-16T09:00:00Z'),
  },
];

module.exports = news;
