/**
 * KrishiSathi - Government Schemes Seed Data
 * 10 real Indian agriculture schemes with accurate details
 */

const schemes = [
  {
    name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    shortName: 'PM-KISAN',
    description: 'PM-KISAN is a central sector scheme providing income support of Rs. 6,000 per year to all landholding farmer families across the country in three equal instalments of Rs. 2,000 each, every four months. The scheme aims to supplement the financial needs of farmers in procuring various inputs to ensure proper crop health and appropriate yields, commensurate with the anticipated farm income. The fund is directly transferred to the bank accounts of the beneficiaries through Direct Benefit Transfer (DBT) mode.',
    benefits: 'Rs. 6,000 per year in three instalments of Rs. 2,000 each, transferred directly to the farmer\'s Aadhaar-linked bank account. Over 11 crore farmers benefit from this scheme. The instalments are released in April-July, August-November, and December-March cycles.',
    eligibility: {
      landHoldingMax: 0,
      landHoldingMin: 0,
      crops: [],
      states: [],
      categories: ['all'],
    },
    documents: ['Aadhaar Card', 'Bank Account (Aadhaar-linked)', 'Land ownership records (khasra/khatauni)', 'Mobile number'],
    applicationUrl: 'https://pmkisan.gov.in',
    deadline: new Date('2026-12-31'),
    status: 'active',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    category: 'subsidy',
  },
  {
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    shortName: 'PMFBY',
    description: 'PMFBY is a comprehensive crop insurance scheme that provides financial support to farmers suffering crop loss or damage arising out of unforeseen events like natural calamities, pests, and diseases. The scheme covers all food crops, oilseeds, annual commercial/horticultural crops for which past yield data is available. It operates on an area approach basis using technology including satellite imagery, remote sensing, drones, and smartphones for quick claim settlement.',
    benefits: 'Premium rate: 2% for Kharif crops, 1.5% for Rabi crops, 5% for annual commercial/horticultural crops. Government subsidises the remaining premium. Sum insured is equal to the scale of finance (cost of cultivation). Claims are settled within 2 months of harvest. Add-on coverage for prevented sowing, post-harvest losses (up to 14 days), and localized calamities.',
    eligibility: {
      landHoldingMax: 0,
      landHoldingMin: 0,
      crops: ['cotton', 'rice', 'wheat', 'maize', 'groundnut', 'soybean', 'sugarcane', 'onion', 'chilli', 'tomato'],
      states: [],
      categories: ['all'],
    },
    documents: ['Aadhaar Card', 'Bank account details', 'Land records (khata/record of rights)', 'Sowing certificate from Patwari/Revenue officer', 'Crop details and area sown'],
    applicationUrl: 'https://pmfby.gov.in',
    deadline: new Date('2026-07-31'),
    status: 'active',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    category: 'insurance',
  },
  {
    name: 'Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)',
    shortName: 'PMKSY',
    description: 'PMKSY aims to ensure access to some means of protective irrigation to all agricultural farms in the country, to produce "per drop more crop" thus bringing much desired rural prosperity. The scheme focuses on creating sources for assured irrigation, extending coverage, improving on-farm water use efficiency, introducing sustainable water conservation practices, and promoting micro-irrigation systems like drip and sprinkler irrigation. The "Har Khet Ko Pani" component ensures end-to-end solutions in irrigation supply chain.',
    benefits: 'Subsidy of 55% for small and marginal farmers and 45% for other farmers on micro-irrigation systems (drip and sprinkler). Additional top-up subsidy by state governments brings effective subsidy to 80-90% in many states. Coverage for water harvesting structures, farm ponds, watershed development, and canal distribution systems.',
    eligibility: {
      landHoldingMax: 0,
      landHoldingMin: 0,
      crops: [],
      states: [],
      categories: ['all'],
    },
    documents: ['Aadhaar Card', 'Land records', 'Bank account details', 'Quotation from empanelled supplier (for micro-irrigation)', 'Caste certificate (if applicable for additional benefits)'],
    applicationUrl: 'https://pmksy.gov.in',
    deadline: new Date('2026-12-31'),
    status: 'active',
    ministry: 'Ministry of Agriculture and Farmers Welfare / Ministry of Jal Shakti',
    category: 'irrigation',
  },
  {
    name: 'Kisan Credit Card (KCC)',
    shortName: 'KCC',
    description: 'The Kisan Credit Card scheme provides affordable institutional credit to farmers for their agricultural and allied activity needs. It provides a revolving credit facility with a flexible limit based on land holding, cropping pattern, and scale of finance. The scheme covers short-term crop loans, post-harvest expenses, produce marketing loans, consumption requirements, working capital for maintenance of farm assets and allied activities including dairy, fisheries, and animal husbandry. Modified KCC now includes PM-KISAN beneficiaries for simplified access.',
    benefits: 'Credit limit up to Rs. 3 lakh at concessional interest rate of 7% per annum, with additional 3% interest subvention for prompt repayment (effective rate of 4% p.a.). One-time documentation, flexible repayment options, and personal accident insurance coverage of Rs. 50,000 (death) and Rs. 25,000 (disability). Crop insurance premium can be financed through KCC. Validity of 5 years with annual renewal.',
    eligibility: {
      landHoldingMax: 0,
      landHoldingMin: 0,
      crops: [],
      states: [],
      categories: ['all'],
    },
    documents: ['Aadhaar Card', 'PAN Card (for loans above Rs. 1.6 lakh)', 'Land records / tenancy agreement', 'Passport-size photographs', 'Bank account details', 'Revenue records or cropping pattern details'],
    applicationUrl: 'https://www.pmkisan.gov.in/KCCForm.aspx',
    deadline: new Date('2026-12-31'),
    status: 'active',
    ministry: 'Ministry of Finance / Department of Financial Services',
    category: 'credit',
  },
  {
    name: 'Soil Health Card Scheme',
    shortName: 'SHC',
    description: 'The Soil Health Card scheme provides every farmer a soil health card in a cycle of 2 years, which carries crop-wise recommendations of nutrients and fertilizers required for individual farms. This helps farmers to improve productivity through judicious use of inputs. The card contains information on soil health parameters like pH, electrical conductivity, organic carbon, available nitrogen, phosphorus, potassium, sulphur, zinc, boron, iron, manganese, and copper. Soil testing is done through a network of government and private soil testing laboratories.',
    benefits: 'Free soil testing and analysis for 12 key parameters. Personalized crop-specific fertilizer recommendations to optimize input costs and improve yields. Studies show 8-10% reduction in fertilizer use and 5-6% improvement in crop yields with SHC-based recommendations. Digital soil health cards accessible online. Village-level soil fertility maps for better planning.',
    eligibility: {
      landHoldingMax: 0,
      landHoldingMin: 0,
      crops: [],
      states: [],
      categories: ['all'],
    },
    documents: ['Aadhaar Card', 'Land ownership details', 'Village and survey number', 'Mobile number for SMS alerts and digital card'],
    applicationUrl: 'https://soilhealth.dac.gov.in',
    deadline: new Date('2026-12-31'),
    status: 'active',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    category: 'other',
  },
  {
    name: 'National Mission on Oilseeds and Oil Palm (NMOOP)',
    shortName: 'NMOOP',
    description: 'NMOOP aims to increase the production and productivity of oilseeds and oil palm to reduce India\'s dependence on imported edible oils. The mission provides financial assistance for quality seed distribution, improved production technologies, front line demonstrations, supply of inputs like Gypsum, Pyrite, bio-fertilizers, and plant protection chemicals. Special focus on soybean, groundnut, sunflower, rapeseed-mustard, sesame, niger, and safflower. The National Mission on Edible Oils - Oil Palm (NMEO-OP) has been subsumed under this with enhanced support for oil palm cultivation.',
    benefits: 'Subsidy on certified seeds (25-50% of cost), free distribution of Gypsum and Pyrite for groundnut (Rs. 750/ha for gypsum), sprinkler sets (50% subsidy), plant protection equipment, seed mini-kits, and farm implements. Demonstration plots on farmer fields with full input support. Oil palm: Rs. 29,000/ha planting material subsidy, Rs. 250/plant maintenance for 4 years.',
    eligibility: {
      landHoldingMax: 0,
      landHoldingMin: 0,
      crops: ['groundnut', 'soybean'],
      states: [],
      categories: ['all'],
    },
    documents: ['Aadhaar Card', 'Land records', 'Bank account details', 'Caste certificate (for priority categories)', 'Existing oilseed cultivation proof'],
    applicationUrl: 'https://nmoop.gov.in',
    deadline: new Date('2026-12-31'),
    status: 'active',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    category: 'subsidy',
  },
  {
    name: 'National Agriculture Market (e-NAM)',
    shortName: 'e-NAM',
    description: 'e-NAM is a pan-India electronic trading portal which networks the existing APMC mandis to create a unified national market for agricultural commodities. It promotes uniformity in agriculture marketing by streamlining procedures across mandis, removing information asymmetry between buyers and sellers, and promoting real-time price discovery based on actual demand and supply. Over 1,361 mandis across 23 states and 3 UTs have been integrated on the e-NAM platform. The platform facilitates online trading, quality assaying (using AGMARK parameters), digital payment, and logistic support.',
    benefits: 'Transparent price discovery through online bidding. Farmers can sell produce to buyers across the country, not limited to local mandi traders. Quality-based pricing through standardized assaying. Direct payment to farmer\'s bank account. Reduced intermediary costs - farmers get 15-20% better price realisation. Real-time price information for all mandis. No need for physical presence at mandi for trade.',
    eligibility: {
      landHoldingMax: 0,
      landHoldingMin: 0,
      crops: ['cotton', 'rice', 'wheat', 'maize', 'tomato', 'groundnut', 'soybean', 'onion', 'chilli'],
      states: [],
      categories: ['all'],
    },
    documents: ['Aadhaar Card', 'Bank account details', 'Mandi registration/license', 'Mobile number for OTP-based access', 'Produce details and quality certificate'],
    applicationUrl: 'https://enam.gov.in',
    deadline: new Date('2026-12-31'),
    status: 'active',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    category: 'marketing',
  },
  {
    name: 'Sub-Mission on Agricultural Mechanization (SMAM)',
    shortName: 'SMAM',
    description: 'SMAM aims to increase the reach of farm mechanization to small and marginal farmers and to the regions where availability of farm power is low. The scheme promotes Custom Hiring Centres (CHCs), Hi-Tech Hubs, Farm Machinery Banks for hi-tech and high value farm equipment, and distribution of subsidized farm machinery and implements to individual farmers. The programme also supports creation of awareness and demonstrations of farm machinery and establishment of farm machinery training and testing centres.',
    benefits: 'Subsidy of 40-50% on purchase of agricultural machinery (tractor-mounted, power-operated, and manually-operated equipment). 80% subsidy for establishment of Custom Hiring Centres (CHCs) and Hi-tech Hubs. Eligible equipment includes power tillers, rotavators, laser land levellers, paddy transplanters, happy seeders, combine harvesters, mulchers, seed drills, sprayers, and processing equipment. SC/ST/Women farmers get priority and higher subsidy.',
    eligibility: {
      landHoldingMax: 0,
      landHoldingMin: 0,
      crops: [],
      states: [],
      categories: ['small', 'marginal', 'all'],
    },
    documents: ['Aadhaar Card', 'Land records', 'Bank account details', 'Quotation from authorized dealer', 'Caste certificate (if applicable)', 'Passport-size photographs', 'Previous machinery purchase details (to avoid duplication)'],
    applicationUrl: 'https://agrimachinery.nic.in',
    deadline: new Date('2026-12-31'),
    status: 'active',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    category: 'subsidy',
  },
  {
    name: 'Rashtriya Krishi Vikas Yojana (RKVY-RAFTAAR)',
    shortName: 'RKVY',
    description: 'RKVY-RAFTAAR (Remunerative Approaches for Agriculture and Allied sector Rejuvenation) is a state plan scheme that provides flexibility and autonomy to states in planning and executing agriculture and allied sector development programmes. It incentivises states to increase public investment in agriculture. Key focus areas include pre and post-harvest infrastructure, value addition, agri-business and entrepreneurship development, innovation and agri-tech through incubation ecosystem. The scheme allocates funds based on state agriculture and allied sector expenditure performance.',
    benefits: 'Grants to states for agriculture development projects. 70% funding for general states (90% for NE and hill states) with state matching share. Funds for cold storage, warehouses, food processing units, and market infrastructure. Up to Rs. 25 lakh for agri-startups through RKVY-RAFTAAR Innovation and Agripreneurship component. Skill development and capacity building programmes for farmers and rural youth.',
    eligibility: {
      landHoldingMax: 0,
      landHoldingMin: 0,
      crops: [],
      states: [],
      categories: ['all'],
    },
    documents: ['Aadhaar Card', 'Project proposal (for infrastructure/startup)', 'Land records', 'Bank account details', 'Business plan (for agri-entrepreneurship)', 'Registration with state agriculture department'],
    applicationUrl: 'https://rkvy.nic.in',
    deadline: new Date('2026-12-31'),
    status: 'active',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    category: 'subsidy',
  },
  {
    name: 'Pradhan Mantri Annadata Aay Sanrakshan Abhiyan (PM-AASHA)',
    shortName: 'PM-AASHA',
    description: 'PM-AASHA is an umbrella scheme to ensure Minimum Support Price (MSP) to farmers for their produce. It comprises three sub-schemes: Price Support Scheme (PSS) for procurement of pulses, oilseeds, and copra; Price Deficiency Payment Scheme (PDPS) covering oilseeds where the difference between MSP and selling/modal price is paid directly to the farmer; and Private Procurement and Stockist Scheme (PPSS) where private agencies procure at MSP when government agencies cannot. The scheme aims to address the gap between MSP announcement and actual procurement implementation.',
    benefits: 'Guaranteed MSP-based procurement for notified oilseeds, pulses, and copra. Under PDPS, farmers get the difference between MSP and market price directly in their bank account (up to 25% of MSP). Under PSS, NAFED/FCI/CCI/state agencies procure at MSP. Reduces farmer distress selling below MSP. For 2024-25: Cotton MSP Rs. 7,121, Soybean Rs. 4,892, Groundnut Rs. 6,783 per quintal.',
    eligibility: {
      landHoldingMax: 0,
      landHoldingMin: 0,
      crops: ['cotton', 'groundnut', 'soybean'],
      states: [],
      categories: ['all'],
    },
    documents: ['Aadhaar Card', 'Land ownership/cultivation records', 'Bank account details (for PDPS)', 'Mandi arrival receipt', 'Crop registration with state agriculture department', 'Sowing declaration form'],
    applicationUrl: 'https://farmer.gov.in',
    deadline: new Date('2026-06-30'),
    status: 'active',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    category: 'marketing',
  },
];

module.exports = schemes;
